### ISSUE TITLE
Simple question about output files 

### ISSUE THREAD

**Issue by VladoPortos** [weldr/lorax#1005]
Hello,
I'm bit unclear about the output when I'm making PXE bootable live CD.
The result/ directory  contains:
```
livecd.iso ( --image-name=livecd.iso )
than
live-rootfs.squashfs.img 
vmlinuz-<version>
initramfs-<version>.img 
PXE_CONFIG
```

I assume the livecd.iso is the live cd it made... 
what is live-rootfs.squashfs.img ? PXE_CONFIG specify to boot live-rootfs.squashfs.img as root= does than mean i don't need the livecd.iso  ? ( sorry of stupid question, just it gave me pause )

**Comment by bcl** [comment]
Right, it has the iso appended to the end of the initramfs. Note that you need enough RAM to load it all before it runs, so make sure you give it as much as possible :)
