### ISSUE TITLE
support for root=live:nfs://<ip>

### ISSUE THREAD

**Issue by VladoPortos** [weldr/lorax#1006]
Hello, 
I have spend whole day trying to get this to work (literally) and can't figure this out.

I would like the live cd build using livemedia-creator to be able handle reading the quashfs.img from NFS server ( or tftp ) how ever no matter what I do the live boot via PXE fails with:

`dracut: FATAL: Don't know how to handle 'root=live:nfs://<IP>/live-rootfs.squashfs.img`

I have included:
```
dracut-network
dracut-config-generic

```
in %packages in .ks file

I have tried also adding network into the dracut args ( edited the default value in python file )
`
dracut args = ['--xz', '--add', 'livenet network dmsquash-live convertfs pollcdrom', '--omit', 'plymouth', '--no-hostonly', '--no-early-microcode']`

Nothing helps :(

**Comment by VladoPortos** [comment]
I have done it ! 
- Just in case somebody come across this.... 

Include: nfs-utils in %packages in .ks file

And I have edited: nano /usr/lib/python2.7/site-packages/pylorax/creator.py to add livenet network nfs into dracut args ( would be nice to have example of the arguments in documentation )

Now I'm looking at booted live cd via NFS... im so happy !

**Comment by bcl** [comment]
> And I have edited: nano /usr/lib/python2.7/site-packages/pylorax/creator.py to add livenet network nfs into dracut args ( would be nice to have example of the arguments in documentation )

You can pass those on the cmdline with `--dracut-arg`, no need to edit the source.

**Comment by VladoPortos** [comment]
I know from the manual about the --dracut-arg but not the format how to pass the arguments... put it in quotation marks, or just one after another...
Would this work: 
--dracut-arg "--xz --add livenet network dmsquash-live convertfs pollcdrom --omit plymouth --no-hostonly --no-early-microcode" 

I wasn't sure, so I added it to the source :) 

I have one more question if I can. Do you know if there is any special parameter to make the final result any smaller ? I mean, I think I have taken out of the iso via kickstarter file every package I thought safe, every man page, and other files I could find over internet... yet the final squashed iso is around 800MB. I'm using latest RHEL7 ( pretty much have to use that one )

**Comment by bcl** [comment]
It's a bit awkard, you need to use single quotes, and pass each one with a new `--dracut-arg`:

```
 --dracut-arg='--xz' --dracut-arg='--add livenet network dmsquash-live convertfs pollcdrom' --dracut-arg='--omit plymouth' --dracut-arg='--no-hostonly' --dracut-arg='--no-early-microcode'
```

As far as the final result size, that depends mostly on the package dependencies, there isn't much you can do about the minimum size of things other than go in and manually remove things.
