### ISSUE TITLE
stage2 kernel is needed for FIPS + direct boot

### ISSUE THREAD

**Issue by t184256** [weldr/lorax#1021]
I believe https://github.com/weldr/lorax/pull/926 breaks FIPS + direct kernel boot scenario.
Unless there's yet another kernel copy somewhere, I don't think we can drop the stage2 one.

Please consider reverting #926 

@jstodola

**Comment by bcl** [comment]
Please explain in more detail what you mean by 'direct boot'.

**Comment by t184256** [comment]
Things like this `qemu -kernel vmlinuz -initrd initrd.img -append 'fips=1 ...'`.

Network booting and manually booting with existing bootloaders might also be in the same boat.

**Comment by bcl** [comment]
Have you actually run into a problem with this? When you use qemu like that you need to extract the kernel and initrd from the iso, the kernel in /images/pxeboot/vmlinuz is exactly the same on that is in the rootfs.

**Comment by t184256** [comment]
Yes. At least one of our CIs does OS installation Fedora by directly booting vmlinuz and initrd.img taken from /images/pxeboot and never fetching the iso.

PXE booting [https://docs.fedoraproject.org/en-US/fedora/rawhide/install-guide/advanced/Network_based_Installations] also happens without an iso. All-in-all, I think the /images/pxeboot is a separate and supported installation way.

**Comment by bcl** [comment]
Ah, I see now. Is this really a valid use of fips though? Even with the vmlinuz in the rootfs and passing the check there is no guarantee that was the kernel used by qemu/pxe and as far as I can tell no way to check.

**Comment by t184256** [comment]
Hm, interesting question. I'll have to ask more compliance-versed people.

**Comment by t184256** [comment]
@bcl, strangely enough, the answer is "verifying the kernel residing in stage2 is as solid as verifying the kernel normally residing in boot: there is a good enough assurance that the kernel image is the same thing as what is running". So, as long as you ensure you're booting the same kernel through some external means this is fine. But there still has to be a self-check, you can't make it all-external. Compliance world is a weird one for sure.

So, apparently, it's a valid scenario broken here.

**Comment by bcl** [comment]
Thanks, I'll revert this change in Fedora 33.

**Comment by bcl** [comment]
Updated in lorax-33.4-1
