### ISSUE TITLE
composer-cli suggests lorax-composer instead of osbuild-composer

### ISSUE THREAD

**Issue by stefwalter** [weldr/lorax#1025]
As I understand it in Fedora we've switched from defaulting to the lorax-composer backend to the osbuild-composer backend. 

The composer-cli suggested I use lorax-composer, and as a new user this confused me. I thought maybe I was using the wrong command line tool to access osbuild-composer.

Example:

```
# composer-cli providers list
2020-05-29 11:04:29,633: Cannot access '/run/weldr/api.socket'. Is lorax-composer running and this user allowed to access it?
```

**Comment by stefwalter** [comment]
CC @larskarlitski 

Lars suggested I start osbuild-composer, after which the above message went away. Nevertheless, this (very minor issue) may be confusing for new users.

**Comment by stefwalter** [comment]
```
$ rpm -qa | grep composer
osbuild-composer-worker-11-1.fc32.x86_64
cockpit-composer-18-1.fc32.noarch
composer-cli-32.9-1.fc32.x86_64
osbuild-composer-11-1.fc32.x86_64
```

**Comment by bcl** [comment]
I've updated the docs to mention both, and WELDR API server, I can do the same for this error message.

**Comment by bcl** [comment]
Updated in lorax-33.4-1
