### ISSUE TITLE
Listing providers fails with "Expecting value"

### ISSUE THREAD

**Issue by stefwalter** [weldr/lorax#1026]
I'm a new user unfamiliar with what "providers" are ... trying to understand from "man composer-cli" ... 

When I try to list providers, I think I'm getting an error:

```
# composer-cli providers list
2020-05-29 11:22:29,980: Expecting value: line 1 column 1 (char 0)
# composer-cli providers list aws
2020-05-29 11:23:53,403: Expecting value: line 1 column 1 (char 0)
# rpm -qa | grep composer
osbuild-composer-worker-11-1.fc32.x86_64
cockpit-composer-18-1.fc32.noarch
composer-cli-32.9-1.fc32.x86_64
osbuild-composer-11-1.fc32.x86_64
```

**Comment by bcl** [comment]
osbuild-composer doesn't support the upload commands, including provider, except as part of the start compose command, so this is actually a osbuild-composer bug (or decision to make about supporting it, since upload in osbuild-composer is implemented differently).
