### ISSUE TITLE
Add example config files or documentation for config files

### ISSUE THREAD

**Issue by fager** [weldr/lorax#1043]
The lorax-composer.service failed constantly because the server is located behind a proxy.

The problem was fixed by adding the following code to the configuration file:

```
[dnf]
proxy = http://proxy.example.com:8080
```

But i takes a while to figure that out. A Documentation about the config files or some example-files would by very helpfull.

**Comment by bcl** [comment]
lorax-composer has been removed. Please use osbuild-composer instead. https://www.osbuild.org/
