### ISSUE TITLE
Add Live Image for PXE Boot output type for Lorax Composer

### ISSUE THREAD

**Issue by loicalbertin** [weldr/lorax#1044]
Hi,

It will be great if we can build  Kernel+Initrd+Squashfs images using `lorax-composer`.

`livemedia-creator` already supports a [Live Image for PXE Boot](https://weldr.io/lorax/rhel8-branch/livemedia-creator.html#live-image-for-pxe-boot) output using the `--make-pxe-live` switch.

I already made an experimentation following [our ``adding output types`` guide](https://weldr.io/lorax/rhel8-branch/lorax-composer.html#adding-output-types). If you are ok I can open a PR in next few days to have you feedback on the implementation.

Thanks & have a nice day!
Loïc

**Comment by bcl** [comment]
Thanks, but at this time lorax-composer is deprecated and being replaced by https://github.com/osbuild/osbuild-composer/
Could you open an issue over there with a description of your use case?

**Comment by loicalbertin** [comment]
Hi @bcl,

Thanks for your feedback, that's too bad, I didn't notice on weldr website that lorax-composer is deprecated...

Anyway, I opened an issue on osbuild.
