### ISSUE TITLE
macboot is really only supported on x86_64, make the default more intelligent

### ISSUE THREAD

**Issue by bcl** [weldr/lorax#1045]
https://pagure.io/releng/issue/9601 pointed out that having macboot enabled on non-x86 EFI builds really doesn't make sense.
Should probably set the default based on the arch.

**Comment by AdamWill** [comment]
I actually found it's [simpler to do this in Koji](https://pagure.io/koji/pull-request/2373).

**Comment by bcl** [comment]
For Fedora, yes. But for normal users on the cmdline it might be nice if it would Just Work for their arch.
