### ISSUE TITLE
Impossible to select non-default module version

### ISSUE THREAD

**Issue by rbgarga** [weldr/lorax#1054]
When I added a package that depends of nginx 1.16.x to blueprint it fails with following message:

```
An error occurred while trying to get blueprint contents.

TNSR: There was a problem depsolving [('tnsr-release', '*')]: Problem: package
tnsr-release-202007290345-1~b2878.el8.noarch
requires nginx-mod-http-auth-pam >= 1.5.1-24~g0dd0eb0~b2853, but none of the providers can be installed -
package nginx-mod-http-auth-pam-1.5.1-24~g0dd0eb0~b2853.el8.x86_64 requires nginx >= 1:1.16.1, but none
of the providers can be installed - conflicting requests - package
nginx-1:1.16.1-1.module_el8.1.0+250+351caf85.x86_64 is filtered out by modular filtering```

And I couldn't find any place on documentation about how to select a different module version

**Comment by bcl** [comment]
Sorry, but we don't support modules so you can only select packages provided in the default stream.

**Comment by Rtoax** [comment]
> Sorry, but we don't support modules so you can only select packages provided in the default stream.

Hi, lorax Support module yet?

**Comment by bcl** [comment]
No, there are no plans to support modules. Also if you are using lorax-composer you should switch to osbuild-composer which is the replacement for it. See https://osbuild.org and https://github.com/osbuild/osbuild-composer/
