### ISSUE TITLE
composer-cli sources add should accept a repo file

### ISSUE THREAD

**Issue by msehnout** [weldr/lorax#1066]
The problem: When running `composer-cli sources info`, the output is a repo file but the exact output cannot be fed into `composer-cli sources add` because this one only accepts TOML specification. This seems inconsistent.

Furthermore when naively turning the repofile to a TOML, a user can easily introduce subtle errors by using `baseurl` instead of `url` (the first one is used in repo file, the second one in sources specification). Neither lorax-composer, nor osbuild-composer requires "url" to be part of the specification, but osbuild-composer then fails during the depsolv phase with completely unrelated error:
```
[2020-08-28T07:30:47.514Z]     "errors": [
[2020-08-28T07:30:47.514Z]         {
[2020-08-28T07:30:47.514Z]             "id": "BlueprintsError",
[2020-08-28T07:30:47.514Z]             "msg": "targetimage: unexpected end of JSON input"
[2020-08-28T07:30:47.514Z]         }
[2020-08-28T07:30:47.514Z]     ]
```

To improve the user experience we should:
 * improve [documentation](https://weldr.io/lorax/f29-branch/composer-cli.html) with specific examples of `sources add` usage
 * warn the user that the "url" is missing (or fail in osbuild-composer)

**Comment by bcl** [comment]
The output is TOML, but the id is the section name in the output which is why it can't be fed back in using 'add'.

eg.
```
[root@localhost ~]# cat bcl.toml
id = "bcl"
name = "bcl"
type = "yum-baseurl"
url = "http://192.168.101.34:8000/rhel/rhel8.3.0/BaseOS/"
check_gpg = true
check_ssl = true
system = true
```

```
[root@localhost ~]# composer-cli sources info bcl
[bcl]
name = "bcl"
type = "yum-baseurl"
url = "http://192.168.101.34:8000/rhel/rhel8.3.0/BaseOS/"
check_gpg = true
check_ssl = true
system = false
```
Missing the `type` or `url` should be an immediate error. We can probably also be more flexible about the id and pick that up from the section if it is missing (v1 changed the behavior, name used to be what is now called id, and name is now used for longer descriptions).

**Comment by bcl** [comment]
I'm going to close this and we can continue in https://github.com/osbuild/osbuild-composer/issues/951 since the change will be in the api server, not in composer-cli.
