### ISSUE TITLE
Build artefacts are in source tree under git

### ISSUE THREAD

**Issue by asashnov** [weldr/lorax#1071]
It's considered to be a bad practice to put build artefacts (not the original work) under sources system control.

In particular, we should remove huge docs/html/searchindex.js file. It is big, and modified every time any of the files changed.

**Comment by bcl** [comment]
Generally I agree, but we decided to include the sphinx generated html docs in git to make it easier for people to read them, so it really can't go away. FWIW the docs are in a separate rpm package in Fedora so you don't have to install it.

**Comment by asashnov** [comment]
Storing generated file violating the idea of tracking changes made by humans.

https://readthedocs.org/ or just upload generated documentation as .zip to 'Releases' can serve better.

Imagine a situation of having several PRs in parallel. When the first developer has accepted their changes to 'master', another developer should merge all the changes in generated documents also.
