### ISSUE TITLE
(Feature request) loopback.cfg files for booting Live ISOs from hard disk

### ISSUE THREAD

**Issue by probonopd** [weldr/lorax#1090]
Please consider generating `loopback.cfg` files.

A `loopback.cfg` is basically just a `grub.cfg` that's designed to be used to boot a live distribution from an ISO file on a filesystem rather than an actual physical CD. 

This allows it to make it easy to boot many different ISOs e.g., from an SSD like this:

![image](https://user-images.githubusercontent.com/2480569/96296970-ac6ed380-0fdf-11eb-8490-e99d7635fa3a.png)

Without a `loopback.cfg` file, systems like https://www.ventoy.net/en/index.html and https://github.com/probonopd/SystemImageKit have to take care of each distribution (version) and, as a result, take a lot of maintenance work and/or tend to break frequently, whereas with a `loopback.cfg` file it "just works" without the tools having to play "catch up" with new distribution releases.

Here is the specification: 
https://www.supergrubdisk.org/wiki/Loopback.cfg

Many distributions have started shipping those, including:
* Manjaro
* Ubuntu
* Grml

@Conan-Kudo hinted that with the following, a main showstopper that had prevented  `loopback.cfg` files from being used in the past might be removed: https://fedoraproject.org/wiki/Changes/OptimizeSquashFSOnDVDByRemovingEXT4FilesystemImageLayer

**Comment by bcl** [comment]
* Would this be for both the boot.iso and the live iso?
* Does it work with UEFI?
* Does it work on all architectures?

It sounds like a pretty minimal change, but I don't use this kind of booting at all so someone is going to need to come up with a working loopback.cfg that I can turn into a template, and test the results for me.

Changes should be:
* Add a template loopback.cfg file to the supported architectures under `share/templates.d/99-generic/live/config_files/`
* Install it to /boot/grub/ in `share/templates.d/99-generic/live/x86.tmpl` (and other arches)
* Replace placeholder values with correct ones in the same way we do for isolinux.cfg

**Comment by probonopd** [comment]
> Would this be for both the boot.iso and the live iso?

It would be most helpful for Live ISOs, which this request is about. But if people find it useful for boot.iso, it could be used there as well.

> Does it work with UEFI?

Yes.

> Does it work on all architectures?

It works on all architectures which GRUB works on, as it is basically just a GRUB config file.

**Comment by probonopd** [comment]
Thank you very much @bcl. 
(Four years later, I need to find out which Live CDs are made with Lorax, I forgot.)

**Comment by Conan-Kudo** [comment]
Is this actually done? I didn't see anything for it...

**Comment by probonopd** [comment]
Was referring to 

![image](https://github.com/user-attachments/assets/87dbce38-28cf-42c0-b1e3-1b0f386bc09b)

in the assumption that "completed" means "implemented"...

**Comment by bcl** [comment]
You can thank github for hiding the different ways to close things. It's not being worked on, it is ancient, so I closed it. Feel free to submit PRs :)

**Comment by probonopd** [comment]
So do you think that having `loopback.cfg` support for booting Live ISOs from hard disk would be a good idea?

**Comment by bcl** [comment]
Given how long this issue sat without anyone working on it, no :)
