### ISSUE TITLE
Don't remove openldap libraries in runtime-cleanup.tmpl

### ISSUE THREAD

**Issue by droideck** [weldr/lorax#1098]
Openldap Fedora package now has manual links to its libraries as we are in a process of removing libldap non-threaded libs.
https://fedoraproject.org/wiki/Changes/OpenLDAPwithoutNonthreadedLibraries

This line should be changed/removed.
https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/runtime-cleanup.tmpl#L267

Additionally, could someone, please, clarify what's the purpose of this cleanup?

**Comment by bcl** [comment]
The cleanup template is used to reduce the size of the rootfs filesystem by removing things that aren't actually used during installation.

**Comment by droideck** [comment]
> The cleanup template is used to reduce the size of the rootfs filesystem by removing things that aren't actually used during installation.

Thanks for the explanation!
Could you please also tell me how to move #1099?
It blocks a new release of OpenLDAP on Fedora.

**Comment by bcl** [comment]
I'll merge and do a new build once the new build of openldap hits the repos.

Fixes #1099

**Comment by droideck** [comment]
> I'll merge and do a new build once the new build of openldap hits the repos.
> 
> Fixes #1099

Thank you!
The build is already there but it was untagged (I am not sure if it's possible to tag it back)
https://pagure.io/releng/issue/9859#comment-703396

This is the build:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1645917
