### ISSUE TITLE
Problems using livemedia-creator images for network installation using virt-install

### ISSUE THREAD

**Issue by T0MASD** [weldr/lorax#1104]
I ran livemedia-creator to build custom fedora live. I'm serving `images` dir on http server with .treeinfo from fedora mirror  [checksum] section removed. I'm running
`virt-install --location=http://192.168.122.244:8000/33/x86_64/` kernel and initrd are downloaded (as seen from http server logs)
```
Jan 04 23:48:33 uola-qa python3[2578]: 192.168.122.1 - - [04/Jan/2021 23:48:33] "GET /33/x86_64/.treeinfo HTTP/1.1" 200 -
Jan 04 23:48:33 uola-qa python3[2578]: 192.168.122.1 - - [04/Jan/2021 23:48:33] "HEAD /33/x86_64/images/pxeboot/vmlinuz HTTP/1.1" 200 -
Jan 04 23:48:33 uola-qa python3[2578]: 192.168.122.1 - - [04/Jan/2021 23:48:33] "HEAD /33/x86_64/images/pxeboot/initrd.img HTTP/1.1" 200 -
Jan 04 23:48:33 uola-qa python3[2578]: 192.168.122.1 - - [04/Jan/2021 23:48:33] "GET /33/x86_64/images/pxeboot/vmlinuz HTTP/1.1" 200 -
Jan 04 23:48:33 uola-qa python3[2578]: 192.168.122.1 - - [04/Jan/2021 23:48:33] "GET /33/x86_64/images/pxeboot/initrd.img HTTP/1.1" 200 -
```
The vm fails to Switch Root... 

```
[  OK  ] Reached target Switch Root.
         Starting Switch Root...
[FAILED] Failed to start Switch Root.
See 'systemctl status initrd-switch-root.service' for details.
```
looking at 'systemctl status initrd-switch-root.service' 
```
● initrd-switch-root.service - Switch Root
     Loaded: loaded (/usr/lib/systemd/system/initrd-switch-root.service; static)
     Active: failed (Result: exit-code) since Tue 2021-01-05 00:17:25 UTC; 31s ago
    Process: 658 ExecStart=/usr/bin/systemctl --no-block switch-root /sysroot (code=exited, status=1/FAILURE)
   Main PID: 658 (code=exited, status=1/FAILURE)
        CPU: 8ms

Jan 05 00:17:25 fedora systemd[1]: Starting Switch Root...
Jan 05 00:17:25 fedora systemctl[658]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
Jan 05 00:17:25 fedora systemd[1]: initrd-switch-root.service: Main process exited, code=exited, status=1/FAILURE
Jan 05 00:17:25 fedora systemd[1]: initrd-switch-root.service: Failed with result 'exit-code'.
Jan 05 00:17:25 fedora systemd[1]: Failed to start Switch Root.
Jan 05 00:17:25 fedora systemd[1]: initrd-switch-root.service: Triggering OnFailure= dependencies.
```

The error appears to be because '/sysroot' does not seem to be an OS tree:
```
Jan 05 00:17:25 fedora systemctl[658]: Failed to switch root: Specified switch root path '/sysroot' does not seem to be an OS tree. os-release file is missing.
```

**Comment by bcl** [comment]
I'm not sure what virt-install does to setup the cmdline, but my guess would be that it doesn't know how to deal with live images. Take a look at the output of `cat /proc/cmdline` from the dracut shell that shows up when it fails to boot and see if that sheds any light on it.

**Comment by T0MASD** [comment]
Hi, thanks for getting back and apologies for not including that straight away.
My virt-install command:
```
virt-install \
    --name uola-throwaway \ 
    --ram '5120' \
    --os-type linux \
    --os-variant fedora30 \
    --virt-type kvm \
    --graphics none \
    --connect qemu:///system \
    --noautoconsole \
    --disk=/storage/ram/images/throwaway.vda.x86_64.qcow2,bus=virtio,format=qcow2 \
    --location=http://192.168.122.1:8000/33/x86_64/ \
    --initrd-inject /tmp/uola-throwaway-3j_3zbae.ks \
    --extra-args=inst.ks=file:/uola-throwaway-3j_3zbae.ks console=ttyS0 net.ifnames=0 biosdevname=0
```
When boot stops and I enter the shell, /proc/cmdline is 
```
:/root# cat /proc/cmdline 
inst.ks=file:/uola-throwaway-3j_3zbae.ks console=ttyS0 net.ifnames=0 biosdevname=0 inst.repo=http://192.168.122.1:8000/33/x86_64/
:/root# 
```
Just in case I've also uploaded contents of /run/initramfs/rdsosreport.txt to https://gist.github.com/T0MASD/272c8da7d5928e86c922a880724ec371

As a comparison, cat /proc/cmdline  when using kernel and initrd from https://mirror.aarnet.edu.au/pub/fedora/linux/releases/33/Everything/x86_64/os/images/pxeboot/
```
[tomas@live ~]$ cat /proc/cmdline 
inst.ks=file:/uola-throwaway-x0qucann.ks console=ttyS0 net.ifnames=0 biosdevname=0 inst.repo=http://192.168.122.1:8000/33/x86_64/
```
p.s. edora kernel and initrd with image that was built using livemedia-creator boots up. Maybe it's something in how initrd is generated by lorax?

Kickstart I'm using to generate live image https://gist.github.com/T0MASD/b42c78496fdd7a4cfa1f367f6bfa97c6

**Comment by bcl** [comment]
Ah, ok. It won't work like that :) In the boot.iso case it has anaconda-dracut in the initrd, which knows how to use inst.repo to pull the root filesystem from the repo (install.img), and mount it. With your live image the initrd doesn't know where to get the rootfs from or how to mount it.

livemedia-creator has an option to build a PXE bootable live image. See https://weldr.io/lorax/livemedia-creator.html#live-image-for-pxe-boot the output will include the directory tree as well as the PXE cmdline needed.

**Comment by T0MASD** [comment]
Thank you, I ran livemedia-creatro with `--make-pxe-live` option. I had a look at PXE_CONFIG which had:
```
# PXE configuration template generated by livemedia-creator
kernel <PXE_DIR>/vmlinuz-5.9.16-200.fc33.x86_64+debug
append initrd=<PXE_DIR>/initramfs-5.9.16-200.fc33.x86_64+debug.img root=live:<URL>/live-rootfs.squashfs.img 
```
Which lead me to add `root=live:<URL>/live-rootfs.squashfs.img` to my  --extra-args now the root is switched ok, however injected kickstart file is not carried over from initrd (makes sense). It appears I need to execute anaconda from within stage1. I'll try using `anaconda-dracut`
