### ISSUE TITLE
allow dropping memtest86

### ISSUE THREAD

**Issue by nirik** [weldr/lorax#1114]
We are looking to drop memtest86

It's bios only and other issues. 

See: https://pagure.io/fedora-kickstarts/pull-request/754 and discussion on devel list. 

We need to remove it from templates or composes fail. I will revert the kickstarts change until we have the lorax side ready.

**Comment by bcl** [comment]
I've been following the thread on fedora-devel, but it looked to me like there were still use cases for it. It doesn't really hurt to keep it, but it may also be useful to add an entry to pcmemtest -- although unless things have changed that also has its own set of problems (eg. doesn't work with secureboot).

**Comment by nirik** [comment]
Yeah, I thought we could just git rid of it, but I guess it's not fully clear. :(

**Comment by bcl** [comment]
Dropped by #1169
