### ISSUE TITLE
xorg-x11-server-utils no longer exists in rawhide need to adjust templates

### ISSUE THREAD

**Issue by nirik** [weldr/lorax#1117]
Per https://bugzilla.redhat.com/show_bug.cgi?id=1932754 xorg-x11-server-utils has been broken up into seperate packages. 

lorax tries to install it and fails. 

It's unclear which if anything we need from that package. I guess we could try just dropping it and see what else breaks? 
Or do some testing and see if we need some of the new split packages installed?

**Comment by nirik** [comment]
Looks like we later remove all the package except xrandr and xrdb so just installing those should do it. 

I'm gonna do a quick/dirty patch downstream in rawhide for now and we can fix this for good after that.

**Comment by whot** [comment]
based on what the patch does, this seems to be correct, thanks!

**Comment by bcl** [comment]
> Looks like we later remove all the package except xrandr and xrdb so just installing those should do it.

Also xhost which is used in anaconda's listinst-setup.sh script.

**Comment by bcl** [comment]
Which I see you included with your patch. Could you make a PR for this when the rawhide compose passes?
