### ISSUE TITLE
Is there any documentation for selected fonts in runtime-install.tmpl?

### ISSUE THREAD

**Issue by pnemade** [weldr/lorax#1124]
I see lorax keeps some fonts list in https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/runtime-install.tmpl#L147 file. I would like to know how this list has been determined?

Basically we want see fonts listed in comps mostly as default be listed in lorax. e.g. we have no way to understand why below fonts are added in lorax, for which locale?

- aajohan-comfortaa-fonts
- bitmap-fangsongti-fonts
- sil-padauk-book-fonts
- sil-scheherazade-fonts

**Comment by bcl** [comment]
It's hard to tell exactly why they are included. The templates do not install comps groups, just packages, and I do see one recent commit that adjusted things to match comps (commit 7d7d158399e7af6b8e681b361cca10fbb94156b6)
