### ISSUE TITLE
Entirely Purging "Stock" kernel package to be replaced by kernel-ml or kernel-lt from ELRepo.

### ISSUE THREAD

**Issue by abotelho-cbn** [weldr/lorax#1135]
Hi all, I'm currently trying to build an ISO using livemedia-creator to be used as our master ISO image for our baremetal installs.  We are looking to purge the default "kernel" package with "kernel-ml" or "kernel-lt" from ELRepo. This is on AlmaLinux 8, but I imagine this should be the same as CentOS/RHEL. The packaged Lorax version is 28.14.55.
I have a dedicated baremetal installation of AlmaLinux setup on a machine to run Lorax/livemedia-creator directly.

Here is the command I am using: `livemedia-creator --project="AlmaLinux" --make-iso --no-virt --ks kickstart.ks --iso almalinux.iso`

AlmaLinux ships with two templates: 80-rhel and 99-generic. I've tried both, where the line kernel section in runtime-install.tmpl is adjusted accordingly:
```
## kernel and firmware
## NOTE: Without explicitly including kernel-modules-extra dnf will choose kernel-debuginfo-*
##       to satify a gfs2-utils kmod requirement
installpkg kernel-ml kernel-ml-modules kernel-ml-modules-extra
```

Here is the contents of the kickstart.ks file:
```
rootpw rootpassword
zerombr
clearpart --all
bootloader --location=mbr
part swap --size=512
part / --size=4096 --fstype=ext4
shutdown
url --url="https://repo.almalinux.org/almalinux/8.3/BaseOS/x86_64/kickstart/"
repo --name=AppStream --baseurl="https://repo.almalinux.org/almalinux/8.3/AppStream/x86_64/os/" --install --excludepkgs=kernel
repo --name=PowerTools --baseurl="https://repo.almalinux.org/almalinux/8.3/PowerTools/x86_64/os/" --install --excludepkgs=kernel
repo --name=HighAvailability --baseurl="https://repo.almalinux.org/almalinux/8/HighAvailability/x86_64/os/" --install --excludepkgs=kernel
repo --name=elrepo-kernel --baseurl="https://elrepo.org/linux/kernel/el8/x86_64/" --install
repo --name=elrepo-release --baseurl="https://elrepo.org/linux/elrepo/el8/x86_64/" --install
repo --name=elrepo-extras --baseurl="https://elrepo.org/linux/extras/el8/x86_64/" --install
network --bootproto=dhcp --activate --onboot=on
selinux --disabled
firewall --enabled --ssh
%post
#yum makecache && yum update -y
passwd -d root > /dev/null
cat /dev/null > /dev/fstab
# Remove random-seed
rm /var/lib/systemd/random-seed
# Clear /etc/machine-id
rm /etc/machine-id
touch /etc/machine-id
%end
%packages
@core
-kernel
-kernel-devel
-kernel-tools-libs
-kernel-tools
-kernel-headers
-kernel-modules
-kernel-modules-extra
kexec-tools
dracut-live
dracut-config-generic
grub2-efi
grub2
dracut-network
dracut-config-rescue
shim
tar
syslinux
memtest86+
anaconda
kernel-ml
kernel-ml-devel
kernel-ml-tools
kernel-ml-tools-libs
kernel-ml-headers
kernel-ml-modules
kernel-ml-modules-extra
%end
```

Despite this, Lorax still rebuilds the stock 4.18 initramfs at the end, and the new ISO does not boot from an error related to a missing 4.18 kernel. I can see it rebuild the initramfs for kernel-ml (5.11 at the moment).
I've tried all sorts of tweaks here and there already, but I'm just about at my wits' end with figuring this out on my own.
There's also an issue where the booting USB containing a built ISO only says "Start AlmaLinux" instead of "Install AlmaLinux" on the boot menu, but I suspect that is more trivial.

Cheers

**Comment by bcl** [comment]
The runtime-install.tmpl is only used for creating an anaconda boot.iso not when creating a live iso with lmc, so changes there won't have any effect.

The iso menu, kernel, etc. are all constructed using the templates in the live/ subdirectory. eg. https://github.com/weldr/lorax/tree/master/share/templates.d/99-generic/live

The x86.tmpl picks kernels from the boot partition, but that's populated using this function:
https://github.com/weldr/lorax/blob/master/src/pylorax/treebuilder.py#L380

which expects a certain format for the vmlinuz file. What do the kernel-ml files look like? I suspect it is skipping them because of their names. If you look at the livemedia.log there should be a debug line in there listing the kernels it found. eg.

    kernels=[{'path': 'boot/vmlinuz-5.12.0-0.rc8.191.fc35.x86_64', 'version': '5.12.0-0.rc8.191.fc35.x86_64', 'arch': 'x86_64', 'flavor': None, 'initrd': {'path': 'boot/initramfs-5.12.0-0.rc8.191.fc35.x86_64.img'}}]

If it's not finding your kernels you can either patch lorax to support their names, or change the template.

**Comment by abotelho-cbn** [comment]
> What do the kernel-ml files look like?
vmlinuz has a similar format, with elrepo sandwiched between el8 and x86_64 i.e _vmlinuz-5.11-1-1.el8.elrepo.x86_64_

I'd certainly _prefer_ just modifying template files for this kind of work, for the sake of portability. But honestly Python is portable enough that it would be an adequate solution.

Let's say I want to add a menu entry for *each* kernel it finds. Honestly, that would be totally fine. In fact, it might be preferable to give the sysadmin more flexibility and allow us to use the ISO on a bigger variety of hardware.

> If it's not finding your kernels you can either patch lorax to support their names, or change the template.

It's _finding_ them (I can see it rebuild both the stock kernel and ml kernel initramfs images), but I can't seem to spot where the distinction is made for which ends up in the iso/boot menu.

**Comment by bcl** [comment]
Ah, I see. It's probably because this loop will leave the last one found as vmlinuz
https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/live/x86.tmpl#L58

**Comment by abotelho-cbn** [comment]
Alright, so I suspected something like that. Interesting.
So if I wanted to make sure that the stock kernel never finds its way unto the ISO to hopefully avoid such the condition where only one of the existing kernels get symlinked, where would I remove it? There must be a step where yum installs the kernel, correct?

**Comment by bcl** [comment]
The kernels are installed by anaconda. I'm not sure why it's also installing the regular kernel package, but I'd guess that something depends on it so it gets added to the transaction. You could remove them in the %post section of the kickstart, assuming that the kernel-ml fulfills whatever the requirement was.
