### ISSUE TITLE
where is the option to set packagedir of treeinfo

### ISSUE THREAD

**Issue by zhoupeng** [weldr/lorax#1147]
Hi all,

I use lorax to make a boot.iso, and the use anaconda to genarat a dvd iso.
Then create a VM to boot the dvd iso, it enconter an parameter err reported by anaconda (picture attached)
I am not sure which paramenter may be necessary.

I check the generated .treeinfo, and find the packagedir is not set, but I don't find where is the option to set it.
My generated .treeinfo:
[general]
timestamp = 1620817353.6618755                          
family = myFedora
version = 34                                            
name = myFedora-34                                      
variant =
arch = x86_64
packagedir = ######here is empty, but I It is AppStream for CentOS 8, where to set pls? In my case, the dir is ./Packages and ./repodata
[stage2]
mainimage = images/install.img                          
[images-x86_64]
kernel = images/pxeboot/vmlinuz                         
initrd = images/pxeboot/initrd.img                      
efiboot.img = images/efiboot.img                        
boot.iso = images/boot.iso                              
[images-xen]                                            
kernel = images/pxeboot/vmlinuz                         
initrd = images/pxeboot/initrd.img 
![1](https://user-images.githubusercontent.com/1014132/118683742-36ac3e00-b834-11eb-84bb-4e7085ce378a.png)

**Comment by zhoupeng** [comment]
I figured out this issue. It is because of "release short name validated failed", and in the upstrem repo of productmd, this patch (https://github.com/release-engineering/productmd/commit/a518b022ab5008aaa23021ebc8c2ac3487f70f12) should fix thi bug.

What is the relationship between the two componets of  lorax and productmd please? I figure out the .treeinfo is generated by lorax's x86.tmpl template.

**Comment by bcl** [comment]
Lorax doesn't use productmd, it just writes the .treeinfo as a standard ini style config file.

The bug you are hitting is in productmd, so to keep that from happening you need to make sure the version of productmd used for the boot.iso has the fix in it.

You cannot set the packagedir when using lorax. Usually this is done by the Pungi tool when creating a DVD. The boot.iso doesn't include any packages for the installation, they all come from the network.
