### ISSUE TITLE
losetup fails creating runtime image in Toolbox

### ISSUE THREAD

**Issue by Eonfge** [weldr/lorax#1163]
Hi there. I'm not sure if it's even supported, but I certainly hope so, But I'm running into an error as I follow one of your scripts from the main project page.

### Quickstart
https://weldr.io/lorax/lorax.html#quickstart

```
setenforce 0
lorax -p Eonfge-image -v 34 -r 34 \
  -s http://dl.fedoraproject.org/pub/fedora/linux/releases/34/Everything/x86_64/os/ \
  ./results/  
setenforce 1
```

_It might also be an idea to upate the quickstart with a more current example, but that's a bit beyond the point now._

### Stacktace
```
2021-07-01 22:27:44,665: creating the runtime image
creating the runtime image
Traceback (most recent call last):
  File "/usr/sbin/lorax", line 223, in <module>
    main()
  File "/usr/sbin/lorax", line 204, in main
    lorax.run(dnfbase, opts.product, opts.version, opts.release,
  File "/usr/lib/python3.9/site-packages/pylorax/__init__.py", line 327, in run
    rc = rb.create_ext4_runtime(joinpaths(installroot,runtime),
  File "/usr/lib/python3.9/site-packages/pylorax/treebuilder.py", line 258, in create_ext4_runtime
    imgutils.mkrootfsimg(self.vars.root, joinpaths(workdir, "LiveOS/rootfs.img"),
  File "/usr/lib/python3.9/site-packages/pylorax/imgutils.py", line 136, in mkrootfsimg
    mkext4img(rootdir, outfile, label=label, size=fssize)
  File "/usr/lib/python3.9/site-packages/pylorax/imgutils.py", line 556, in mkext4img
    mkfsimage("ext4", rootdir, outfile, size, mountargs=mountargs,
  File "/usr/lib/python3.9/site-packages/pylorax/imgutils.py", line 525, in mkfsimage
    with LoopDev(outfile, size) as loopdev:
  File "/usr/lib/python3.9/site-packages/pylorax/imgutils.py", line 357, in __enter__
    self.loopdev = loop_attach(self.filename)
  File "/usr/lib/python3.9/site-packages/pylorax/imgutils.py", line 204, in loop_attach
    dev = runcmd_output(["losetup", "--find", "--show", outfile]).strip()
  File "/usr/lib/python3.9/site-packages/pylorax/executils.py", line 373, in runcmd_output
    return execWithCapture(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.9/site-packages/pylorax/executils.py", line 251, in execWithCapture
    return _run_program(argv, stdin=stdin, root=root, log_output=log_output, filter_stderr=filter_stderr,
  File "/usr/lib/python3.9/site-packages/pylorax/executils.py", line 205, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['losetup', '--find', '--show', '/var/tmp/lorax/lorax.lewrdzv8/installroot/images/runtime-workdir/LiveOS/rootfs.img']' returned non-zero exit status 1.
```

**Comment by VladimirSlavik** [comment]
We had a similar problem running lorax in container. (Anaconda ci stuff, build boot.iso.) Did you run it as root? If in container, was it a privileged one? Also, you could try creating two loop devices manually so there's enough of them.

Diaclaimer, these are just ideas to try.

**Comment by Eonfge** [comment]
I can give you a better breakdown of what I meant with Toolbox:

- My system runs Fedora 34
- I created a default Toolbox, which is a Fedora 34 image
- inside the toolbox, 
  - I installed lorax and its dependencies
  - I created a folder in my home 
  - I created a script containing the snippet 
  - I ran the script with sudo rights

Toolbox is really just a podman container with a preset list of permissions and rules. It creates a container based on the image, it mounts a lot of directories including your actual Home, and it gives you a direct shell to work with. Possibly that the /tmp/ is giving issues.

```
            "Binds": [
                "devpts:/dev/pts",
                "/usr:/run/host/usr:rw,rslave,rbind",
                "/run:/run/host/run:rslave,rw,nosuid,nodev,rbind",
                "/run/.heim_org.h5l.kcm-socket:/run/.heim_org.h5l.kcm-socket:rw,rprivate,nosuid,nodev,rbind",
                "/etc:/run/host/etc:rw,rprivate,rbind",
                "/tmp:/run/host/tmp:rslave,rw,nosuid,nodev,rbind",
                "/run/avahi-daemon/socket:/run/avahi-daemon/socket:rw,rprivate,nosuid,nodev,rbind",
                "/media:/media:rslave,rw,rbind",
                "/var:/run/host/var:rslave,rw,rbind",
                "/etc/profile.d/toolbox.sh:/etc/profile.d/toolbox.sh:ro,rprivate,rbind",
                "/run/media:/run/media:rslave,rw,nosuid,nodev,rbind",
                "/boot:/run/host/boot:rslave,rw,rbind",
                "/dev:/dev:rslave,rw,nosuid,rbind",
                "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket:rw,rprivate,nosuid,nodev,rbind",
                "/usr/bin/toolbox:/usr/bin/toolbox:ro,rprivate,rbind",
                "/mnt:/mnt:rslave,rw,rbind",
                "/run/user/1001:/run/user/1001:rw,rprivate,nosuid,nodev,rbind",
                "/home/kevin:/home/kevin:rslave,rw,rbind"
            ],
```

**Comment by VladimirSlavik** [comment]
OK, in that case the setup is really very similar to our github action / workflow. So here's what you need:
- Create (at least) two loop devices on the *host*
- Run lorax in a *privileged* container

Note that lorax does not seem to free the loop devices properly if it does, so if you just re-run the command within the toolbox container, too bad, now you need two more loop devices made.

In the workflow, we tear down the devices after lorax is done, so that the next run won't have them stuck. Maybe you can do that too. The code (shell script of sorts, really) is written with the expectation that the same system will run it many times over its life, so the same should apply to your situation. I *think* that the devices can be destroyed with certain success only if the container with lorax exited, though.

See for yourself...
https://github.com/rhinstaller/anaconda/blob/master/.github/workflows/kickstart-tests.yml#L151
