### ISSUE TITLE
Cant find live-iso type

### ISSUE THREAD

**Issue by QCU87Z** [weldr/lorax#1188]
Morning,

Hoping this is the correct package. I am attempting to create a iso to boot Fedora with using lorax through composer-cli

When I list the types available live-iso isn't available. What provides that type to lorax.

This is all being done on a up to date Fedora34 system. I only have ami, fedora-iot-cimmit openstack qcow2 chd and vmdk available to me.

Cheers

**Comment by bcl** [comment]
osbuild-composer is the new backend, and they decided to drop the live iso type that was previously available with lorax-composer, sorry about that.

You can still use livemedia-creator to make a live iso, it's a bit more work, but see the docs here:

https://weldr.io/lorax/livemedia-creator.html#quickstart
