### ISSUE TITLE
[BUG] OSTree Repo based builds fail installation

### ISSUE THREAD

**Issue by ACertainTopfi** [weldr/lorax#1191]
First of all, please excuse if this is not the proper venue to report this issue. I am currently uncertain whether this issue is predominantly connected to OSTree, Anaconda, Lorax or the wider Silverblue/Atomic/CoreOS projects.
**Describe the bug**
Using Lorax to create an OSTree installer (Silverblue) .iso file based on a .yaml file works with no errors reported in the log, yet installing via the .iso file does not work due to an unusual error (“The command ‘cp -r -r /mnt/sysroot/usr/lib/ostree-boot/loader /mnt/sysimage/boot’ exited with the code 1.”, see also screenshot below). This happens regardless of version, or Silverblue spin even when using the official .yaml files hosted at [https://pagure.io/workstation-ostree-config.git](https://pagure.io/workstation-ostree-config.git).

**To Reproduce**
I have attached a script I use to automate the described steps below.
1. Install Lorax and RPM-OSTree via dnf or rpm on a fresh installation of Fedora 35 Workstation
2. Clone https://pagure.io/workstation-ostree-config.git and https://pagure.io/fedora-lorax-templates.git into a local folder
3. Initialize and Compose a new repo based on a .yaml file inside the workstation-ostree-config folder
4. Execute Lorax with ostree_install_repo and ostree_update_repo pointing to the created local repository
5. After Lorax has finished the build process, try installing the created .iso in a hypervisor or phisical device
6. Encounter error (“The command ‘cp -r -r /mnt/sysroot/usr/lib/ostree-boot/loader /mnt/sysimage/boot’ exited with the code 1.”, see also screenshot below)

**Expected behavior**
The .iso should install as expected when basing a new image on a repository generated via the official ostree-config files.

**Script**
The following script does all described steps aside from the installation of OSTree and Lorax building the .iso based on the official Fedora 35 Silverblue GNOME edition. It leads to the described behavior.

```
mkdir iso && cd iso
git clone -b f35 https://pagure.io/workstation-ostree-config.git
git clone -b f35 https://pagure.io/fedora-lorax-templates.git
mkdir ostree_repo
ostree init --repo=ostree_repo
rpm-ostree compose --unified-core tree --repo=$(pwd)/ostree_repo $(pwd)/workstation-ostree-config/fedora-silverblue.yaml

exec lorax  --product=Fedora \
                --version=35 \
                --release=20211104 \
                --source=https://kojipkgs.fedoraproject.org/compose/35/latest-Fedora-35/compose/Everything/x86_64/os/ \
                --variant=Silverblue \
                --nomacboot \
                --volid=Fedora-SB-ostree-x86_64-35 \
                --add-template=$(pwd)/fedora-lorax-templates/ostree-based-installer/lorax-configure-repo.tmpl \
                --add-template=$(pwd)/fedora-lorax-templates/ostree-based-installer/lorax-embed-repo.tmpl \
                --add-template=$(pwd)/fedora-lorax-templates/ostree-based-installer/lorax-embed-flatpaks.tmpl \
                --add-template-var=ostree_install_repo=file://$(pwd)/ostree_repo \
                --add-template-var=ostree_update_repo=file://$(pwd)/ostree_repo \
                --add-template-var=ostree_osname=fedora \
                --add-template-var=ostree_oskey=fedora-35-primary \
                --add-template-var=ostree_contenturl=mirrorlist=https://ostree.fedoraproject.org/mirrorlist \
                --add-template-var=ostree_install_ref=fedora/35/x86_64/silverblue \
                --add-template-var=ostree_update_ref=fedora/35/x86_64/silverblue \
                --add-template-var=flatpak_remote_name=fedora \
                --add-template-var=flatpak_remote_url=oci+https://registry.fedoraproject.org \
                --add-template-var=flatpak_remote_refs="runtime/org.fedoraproject.Platform/x86_64/f35 app/org.gnome.gedit/x86_64/stable" \
                --logfile=$(pwd)/lorax.log \
                --tmp=$(pwd)/temp \
                --rootfs-size=8 \
                $(pwd)/finished
```

**Screenshots**

![2648c07629fdde39e5152e04c1c113f78eee7246](https://user-images.githubusercontent.com/79299376/140779657-7db77fdb-bc18-4af5-84a3-98c7c80135f8.jpeg)

![583e4e8f00107f15fa5382a8b4ea34cbbad89fea](https://user-images.githubusercontent.com/79299376/140779668-d45c10f0-e6d3-410c-91b3-57e95ec8bbc1.png)

**Comment by bcl** [comment]
That looks like a problem with Anaconda. Lorax doesn't really know anything about ostree itself, it's just running the templates you pass to it, so it's also possible that one of them isn't including something that anaconda expects.

Best thing to do is open a bug against anaconda at bugzilla.redhat.com with the logs attached as text/plain files.
