### ISSUE TITLE
How to install custom rpm using livemedia-creator inside mock

### ISSUE THREAD

**Issue by Athwale** [weldr/lorax#1220]
Hi,

I have been trying to install a custom rpm package that I have on my disk into the live system I am building with livemedia-creator which runs inside mock (on Fedora 34). So far I was not successful.

1. I run the creator like this:
`mock -r fedora-34-x86_64 --rootdir /home/$USER/mock --isolation=simple --enable-network --shell "livemedia-creator --ks flat-fedora-live.ks --no-virt --anaconda-arg='--nosave=all' --make-iso --iso-only --iso-name Fedora-34-x86_64.iso --project Fedora-Live --volid Fedora-34 --releasever 34 --resultdir /tmp/fedora-iso"`
2. I have a self-built rpm package on my disk which I need to install into the system.

I have tried using createrepo to make a repository with the package in the mock fedora environment and add that repo to the kickstart used by the creator. But either I did it wrong or it does not work. When I do this, the installation never finishes.

I have tried using the %post --nochroot section of the kickstart but that does not work either.

Is there a way how to get this done?
Thanks.

**Comment by bcl** [comment]
Have you looked at https://weldr.io/lorax/livemedia-creator.html#using-mock-and-no-virt-to-create-images? That's the supported way to run it. I'm not sure --shell/--rootdir/--isolation will work the same way --chroot does.

You can add a repo by doing the following:
* Create a directory for the repo, eg. `/var/tmp/addon-repo/`
* Copy rpms into it
* Run `createrepo /var/tmp/addon-repo/`
* Add it to the mock config:
  `config_opts['plugin_conf']['bind_mount_opts']['dirs'].append(('/var/tmp/addon-repo','/addon-repo/'))`
* Add it to the kickstart:
  `repo --name=addon-repo --baseurl="file:///addon-repo/"`
