### ISSUE TITLE
composer-cli: How does one perform arbitrary configuration before it gets assembled into an image type?

### ISSUE THREAD

**Issue by abotelho-cbn** [weldr/lorax#1223]
Hi all,

We are trying to build images using composer-cli (using lorax-composer, CentOS 7 and AlmaLinux 8). Unfortunately, Blueprints don't really allow enough granularity for certain things we'd like to do. The images we want to deploy need to be 100% complete by the time they get burned on media and installed in the target box. Things like configuration of specific packages, network interfaces, etc. We are even considering running Puppet/Ansible during build time to configure the image. We'd like to do this before the image is assembled into its final format because we'd like to preserve the flexibility of outputting to any image type.

What is the official way of doing this?

It seems like Blueprints are mostly packages and minimal system configuration, and the image type Kickstarts are most for image-type specific things.

PS: I can't for the life of me find documentation on /etc/lorax/lorax.conf and /etc/lorax/composer.conf

Cheers

**Comment by bcl** [comment]
You might be able to package the custom config files, scripts, etc. in your own rpm and add them as an extra source. But I don't think anyone has actually tried doing that. The other alternative is to use livemedia-creator and put your customizations into a %post section.

As for those config files, they aren't documented anywhere other than in the code.
