### ISSUE TITLE
[Feature Request] Support for overriding/adding additional qemu-kvm options with livemedia-creator

### ISSUE THREAD

**Issue by ryanbowen** [weldr/lorax#1256]
It would be nice to be able to override/customize the options passed to `qemu-kvm` by livemedia-creator. Not being able to customize the network devices, especially the IP range that gets used by the guest, has some annoying DNS-related side effects in my environment.

**Comment by bcl** [comment]
I'm reluctant to add any more cmdline args to livemedia-creator, and I don't think there is any nice way to add support for additional args for qemu. I'm open to suggestions though :) Can you use `--no-virt` mode instead? That runs anaconda directly on the host, so the host should match the release you are building, but that should solve any networking problems.
