### ISSUE TITLE
livemedia-creator iso has wrong selinux contexts

### ISSUE THREAD

**Issue by Athwale** [weldr/lorax#1277]
Hi, I recently hit an issue with selinux on the live image built by livemedia-creator.
I built a live iso with the default kickstart file from https://pagure.io/fedora-kickstarts.git
This is my procedure:
```
git clone https://pagure.io/fedora-kickstarts.git
cd fedora-kickstarts/
git checkout -b f35 origin/f35
ksflatten --config fedora-live-workstation.ks -o flat-fedora-live.ks

FEDORA_VER=35
WORKDIR="/home/$USER/test"
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --init
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --install lorax-lmc-novirt grub2-tools-minimal vim-minimal pykickstart coreutils
cp ./flat-fedora-live.ks "$WORKDIR"/builddir
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --isolation=simple --enable-network --shell "livemedia-creator --ks flat-fedora-live.ks --nomacboot --no-virt --anaconda-arg='--nosave=all' --make-iso --iso-only --iso-name Fedora-${FEDORA_VER}-x86_64.iso --project Fedora-Live --volid Fedora-${FEDORA_VER} --releasever ${FEDORA_VER} --resultdir /tmp/fedora-iso"
```
This is what the selinux context looks like when I run the iso:
```
$ ls -Z /usr/sbin
            unconfined_u:object_r:bin_t:s0 abrt-auto-reporting
            unconfined_u:object_r:abrt_exec_t:s0 abrtd
```

Then I rebuilt the same iso from the same kickstart file with a different tool (livecd-creator):
```
FEDORA_VER=35
WORKDIR="/home/$USER/Priprava/test"
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --clean
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --init
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --install livecd-tools coreutils policycoreutils shadow-utils
cp ./flat-fedora-live.ks "$WORKDIR"/builddir
mock -r fedora-"${FEDORA_VER}"-x86_64 --rootdir "$WORKDIR" --isolation=simple --enable-network --shell "livecd-creator --verbose --config flat-fedora-live.ks --fslabel=Image-Label --cache =/var/cache/live"
```
And the system has correct selinux contexts (the same as a fedora iso downloaded from fedora website):
```
$ ls -Z /usr/sbin/
            system_u:object_r:bin_t:s0 abrt-auto-reporting
            system_u:object_r:abrt_exec_t:s0 abrtd
```

Do you have any idea why the image built with lorax has incorrect selinux context on files or how to fix it?
I think it is causing issues with installed services failing to start.
Thanks.

**Comment by bcl** [comment]
SELinux can be tricky to get working with Enforcing on the host. I though we had it sorted out, but it looks like it is still an issue (I'm hitting other problems with the current rawhide, see https://bugzilla.redhat.com/show_bug.cgi?id=2022160). There are several layers involved, and about the only thing you can do is set the host to Permissive (setenforce 0) while running livemedia-creator and see if that helps.

Also, the host should also be F35 otherwise the selinux policy won't match (it is loaded into the host's kernel).

Since livecd-creator is making the correct labels it's likely that the problem here is extra layer of mock + livemedia-creator + unshare + anaconda.

**Comment by Athwale** [comment]
Thanks. I tried the permissive mode and the host is also F35.
The labels are still incorrect unfortunately.

**Comment by bcl** [comment]
So I've poked at this a bit and I think the conclusion is that lmc + mock won't create the right labels. I am not totally sure why, but the combination of running mock, plus lmc running anaconda via unshare, results in them always being `unconfined_u` so my only recommendation is to use lmc on a VM directly, not via mock, if you care about selinux.

**Comment by Athwale** [comment]
@bcl Hi, sorry I need a bit more advice please.
When you say run lmc on a VM directly, do you mean to not use the --no-virt and instead use qemu and the --iso option. 
Or do you mean something else?

And in any case I can not quite figure out what the "Anaconda boot.iso" for the --iso mentioned in the documentation is. 
Is it like any bootable fedora installation iso or something different, and if it is something different, where do I get one? 
Is it somewhere in the docs and I just missed it?
Thanks.

**Comment by bcl** [comment]
Either use a VM with `--no-virt` or use `--iso` with a boot.iso like https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Everything/x86_64/iso/
