### ISSUE TITLE
lorax has an invalid version devel

### ISSUE THREAD

**Issue by dcermak** [weldr/lorax#1278]
If you install lorax on Fedora 36, it will use the version `devel` which is not a valid version according to [pep440](https://peps.python.org/pep-0440/). This is causing issues for tools like poetry, that require your versions to be valid according to PEP 440. Could you please use a valid version?

**Comment by bcl** [comment]
How did you install it? It should only be using 'devel' when it is used directly from the git repo. When packaged it has the version written into `/usr/lib/python3.10/site-packages/pylorax/version.py` and this is what I see on my F36 system:

    $ lorax -V
    lorax-36.8-1

**Comment by dcermak** [comment]
I did this (on Fedora 36):
```ShellSession
$ dnf install lorax
$ pip freeze|grep lorax
lorax===devel
```

**Comment by bcl** [comment]
Interesting. So pip gets the version from the egg-info directory maybe? On lorax that has -deve- in the path. I'll see if I can fix that, thanks!

**Comment by dcermak** [comment]
I think pip takes the version from here: https://github.com/weldr/lorax/blob/913372697cbeb003bf449ee72adec4becaac97ec/setup.py#L34

**Comment by bcl** [comment]
It ends up it was because setup.py tried to import pylorax.version but that means importing pylorax before the dependencies have been installed. So the import failed silently and defaulted to `devel`.
