### ISSUE TITLE
[Question] How to install flatpak from within kickstart

### ISSUE THREAD

**Issue by manujchandra** [weldr/lorax#1285]
Hello,

I have the following lines in %post

```
%post
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub org.keepassxc.KeePassXC -y
%end
```

When I build an ISO, the iso successfully builds, but I get the following error in the logs:

```
18:05:19,708 INF program: error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name
18:05:19,708 INF program: 
18:05:19,708 INF program: Looking for matches?
18:05:19,709 INF program: error: No remote refs found for ?flathub?
18:05:19,709 INF program: Looking for matches?
18:05:19,709 INF program: error: No remote refs found for ?flathub?
```

How do we set the remote and then install a flatpak from a kickstart file?

I am using mock and fedora 37 xfce cfg and kickstart. livemedia-creator is run from within mock env. 

I am able to run `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` from my regular terminal.

Thanks.

**Comment by bcl** [comment]
That sounds like networking either hasn't been enabled, or dns in the chroot isn't setup. You might be able to work around it by copying the /etc/resolv.conf from the host into the chroot. eg.

https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#examples

```
%post --nochroot
cp /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
%end
```

**Comment by manujchandra** [comment]
Hi, Thanks for your reply.

I have:

```
%post --nochroot

cp -fr /builddir/delete_me.md $INSTALL_ROOT/etc/skel
cp /etc/resolv.conf $INSTALL_ROOT/etc/resolv.conf

%end
```

and in 

```
%post 
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub org.keepassxc.KeePassXC -y
%end
```

I am getting the following in logs:

```
13:16:47,394 INF program: error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name
13:16:47,394 INF program: 
13:16:47,395 INF program: Looking for matches?
13:16:47,395 INF program: error: No remote refs found for ?flathub?
13:16:47,395 INF program: Looking for matches?
13:16:47,395 INF program: error: No remote refs found for ?flathub?
13:16:47,395 DBG program: Return code: 1
13:16:47,396 INF program: Running... /bin/sh /tmp/ks-script-oan_nk0b
13:16:47,446 INF program: cp: '/etc/resolv.conf' and '/etc/resolv.conf' are the same file
```

There are two observations
1) It appears that post is getting executed before post --nochroot because the flatpak errors are appearing before the cp error.
2) cp is complaining that the source and destination are same.

In other words, $INSTALL_ROOT is pointing to the mock environment and not the iso.

I am using mock and the iso is being build from within mock env.

Thanks.

**Comment by manujchandra** [comment]
Greetings,

I made another attempt as follows (using mock):

```
%post --nochroot

cp /etc/resolv.conf /mnt/sysimage/etc/resolv.conf

%end
```

as stated in the [docs](https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#examples).

But I got the following error:

```
20:30:08,643 INF program: error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name
20:30:08,643 INF program: 
20:30:08,643 INF program: Looking for matches?
20:30:08,643 INF program: error: No remote refs found for ?flathub?
20:30:08,643 INF program: Looking for matches?
20:30:08,643 INF program: error: No remote refs found for ?flathub?
20:30:08,643 DBG program: Return code: 1
20:30:08,644 INF program: Running... /bin/sh /tmp/ks-script-pzqtlltw
20:30:08,675 INF program: cp: not writing through dangling symlink '/mnt/sysimage/etc/resolv.conf'
```

I think the main error is `cp: not writing through dangling symlink '/mnt/sysimage/etc/resolv.conf'`

Thanks.

**Comment by alinourzad** [comment]
What does a dangling symlink means? a symlink which points to nowhere?
________________________________

**Comment by manujchandra** [comment]
I think I might have to use the `--remove-destination` flag.  Will try and update.

**Comment by bcl** [comment]
This is probably related to systemd and its handling of `/etc/resolv.conf`, it is a symlink to `../run/systemd/resolve/stub-resolv.conf` on my F36 system so I'm currently not sure how to enable DNS in the %post chroot. Maybe writing a normal resolv.conf manually will work as a workaround, but you should probably restore the previous file/symlink when you are done.

**Comment by manujchandra** [comment]
I tried the following:

```
%post --nochroot
cp --remove-destination /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
%end
```

I did not get any errors in the log, so I am assuming the file got copied.

In post I have 

```
%post
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub org.keepassxc.KeePassXC -y
%end
```

But still I am getting the same error:

```
08:56:57,698 INF program: error: Can't load uri https://flathub.org/repo/flathub.flatpakrepo: While fetching https://flathub.org/repo/flathub.flatpakrepo: [6] Couldn't resolve host name
08:56:57,698 INF program: 
08:56:57,698 INF program: Looking for matches?
08:56:57,698 INF program: error: No remote refs found for ?flathub?
08:56:57,699 INF program: Looking for matches?
08:56:57,699 INF program: error: No remote refs found for ?flathub?
```

One hypothesis could be that the post is getting executed before %post --nochroot

**Comment by manujchandra** [comment]
I think I was able to get it working. Flatpaks got installed from kickstart. I will test some more, post the solution and close the issue. Thanks for your help.

**Comment by bcl** [comment]
Anaconda has some documentation on how to do this - https://anaconda-installer.readthedocs.io/en/latest/common-bugs.html#missing-etc-resolv-conf-for-post-scripts
