### ISSUE TITLE
[Question] How to copy files in iso?

### ISSUE THREAD

**Issue by manujchandra** [weldr/lorax#1286]
Hi,

In my kickstart, I have written the following commands:

```
%post --nochroot

cp -fr /home/manuj/delete_me.md $INSTALL_ROOT/etc/skel

%end
```

In my computer's home directory, there is a file called delete_me.md

I want to copy it to the iso's /etc/skel so that when a new/live user is created, the file gets copied to their home directory.

I am getting the following output in the logs:

`18:05:19,746 INF program: cp: cannot stat '/home/manuj/delete_me.md': No such file or directory`

And the file does not get copied. The file is indeed present in `/home/manuj/delete_me.md` but from the error it appears that cp is not able to read it.

Kindly guide my what is the preferred best practice for copying files in the iso? I have noticed that files from `/var/lib/mock/viperos-37-x86_64/root/etc/skel` also do not get copied to the iso. 

Thanks in advance.

**Comment by bcl** [comment]
If you are using mock as you said in #1285 then the file needs to be copied into the mock environment first.

**Comment by manujchandra** [comment]
Hi,

I made another attempt as follows:
```

%post --nochroot

cp -fr /builddir/delete_me.md /mnt/sysimage/etc/skel

%end
```

And this worked! Would still like to know what would be the correct environment variable to use from within mock instead of /mnt/sysimage

The docs say : If your kickstart is being interpreted by the livecd-creator tool, you should replace /mnt/sysimage above with $INSTALL_ROOT.

but my $INSTALL_ROOT is pointing to the mock environment itself.

**Comment by bcl** [comment]
livecd-creator is a different tool. livemedia-creator uses anaconda so the environment is setup by Anaconda's post handling code, and as far as I can see from looking at the current code there aren't any environmental variables setup so /mnt/sysimage/ is correct.
