### ISSUE TITLE
livemedia-creator does not install locales for anaconda-core

### ISSUE THREAD

**Issue by korewaChino** [weldr/lorax#1295]
We're currently trying to build new Ultramarine images for release with a new pipeline without Koji and we've come across an issue: for whatever reason, all the locale fles for `anaconda-core` are not installed in the final image.

Here's our Kickstart file:
https://paste.centos.org/view/dbfc462f

**Comment by Conan-Kudo** [comment]
I have the same problem when building CentOS Stream Hyperscale Workstation 8 images, and I don't understand what's going on.

Our kickstarts: https://pagure.io/centos-sig-hyperscale/spin-kickstarts/tree/c8s
Our latest images (to observe the problem): https://sigs.centos.org/hyperscale/content/spins/workstation/

**Comment by Conan-Kudo** [comment]
I have also observed this problem when producing images with livecd-creator and kiwi-ng, so it might be an Anaconda problem.

**Comment by Conan-Kudo** [comment]
Actually, some digging into Anaconda reveals the problem:

https://github.com/rhinstaller/anaconda/blob/99bba8bd2c115d477db3ea669c8655821f26a204/pyanaconda/modules/payloads/payload/dnf/installation.py#L63-L90

Anaconda sets the RPM locale based on the locale set in the kickstart.

```
# System language
lang en_US.UTF-8
```

What happens is if you drop it?

**Comment by korewaChino** [comment]
> Actually, some digging into Anaconda reveals the problem:
> 
> https://github.com/rhinstaller/anaconda/blob/99bba8bd2c115d477db3ea669c8655821f26a204/pyanaconda/modules/payloads/payload/dnf/installation.py#L63-L90
> 
> Anaconda sets the RPM locale based on the locale set in the kickstart.
> 
> ```
> # System language
> lang en_US.UTF-8
> ```
> 
> What happens is if you drop it?

Isn't the `lang` command required for Anaconda?

**Comment by Conan-Kudo** [comment]
I don't know?

**Comment by korewaChino** [comment]
Rebuilt Ultramarine images without `lang`. Still not working.

https://github.com/Ultramarine-Linux/build-scripts/actions/runs/3709525675/jobs/6288231356

**Comment by Conan-Kudo** [comment]
What about putting that back and changing `%packages` to `%packages --instlangs all`?

https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-9-package-selection

**Comment by korewaChino** [comment]
> What about putting that back and changing `%packages` to `%packages --instLangs all`?
> 
> https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-9-package-selection

Nope, doesn't work.

**Comment by bcl** [comment]
This is likely a problem with anaconda, not livemedia-creator, since that's what lmc uses to do the package install :) Seems like it should hit more than just the anaconda locale files though.

I'd do 2 things -- try doing an install with your kickstart and the boot.iso instead of lmc, just to eliminate variables. If that still fails to install them, file a bug with Anaconda. There may also be useful info in the anaconda logs so make sure to attach them to the bug.

**Comment by lleyton** [comment]
Just a little note. I tried setting the locale in the kickstart to a non-English language (in this case Chinese,) and it seems like the locale is getting installed and set for all other applications properly... except for anaconda.
![image](https://user-images.githubusercontent.com/26487268/208336790-ecc15d0b-4a09-49d6-a3c4-c88ac4fe5136.png)

**Comment by noelmiller** [comment]
Hi folks,

I'm trying to get any langpacks besides english in anaconda for our custom built ISO. Did you find any resolution to this problem? https://github.com/ublue-os/isogenerator
