### ISSUE TITLE
Uncompressed live filesystem image for use with rd.live.ram=1 

### ISSUE THREAD

**Issue by Athwale** [weldr/lorax#1298]
Hi,

I have a question.
I would like to build a live fedora that is copied to ram during boot entirely and runs from ram with the original boot flash disk removed.
I have had partial success with adding the `rd.live.ram=1` dracut option to the grub boot commands.
As described here in the short **booting live images** section: https://github.com/dracutdevs/dracut/blob/master/man/dracut.cmdline.7.asc#booting-live-images
I modified the `/usr/share/lorax/templates.d/99-generic/live/config_files/x86/grub2-efi.cfg` like this:
```
menuentry 'Start @PRODUCT@ @VERSION@' --unrestricted --class fedora --class gnu-linux --class gnu --class os {
       linuxefi @KERNELPATH@ @ROOT@ rd.live.image rd.live.ram=1
       initrdefi @INITRDPATH@
```

But I would like to get rid of the squashfs and use the **Uncompressed live filesystem image** together with `rd.live.overlay=none` and `rd.writable.fsimg=1`
This is also described under the link above.

The documentation mentions `--skipcompress option of the livecd-iso-to-disk` but I am not sure this is required.
I tried the `--make-fsimage` livemedia-creator option, but this does not create a bootable image.

Is it possible to create an uncompressed bootable live image that can work with the copy to ram options?

Thanks.

**Comment by bcl** [comment]
There isn't currently any way to make an uncompressed rootfs for the iso (and no plans to add it). The best way to accomplish this might be to try to add support for this to dracut, since it already copies things to ram it should be possible to modify it to also decompress it when it copies the squashfs root filesystem.
