### ISSUE TITLE
DNF local plugin to speed up builds?

### ISSUE THREAD

**Issue by Athwale** [weldr/lorax#1304]
Hi,
Is it possible to use the dnf local plugin `python3-dnf-plugin-local` to cache packages between builds?
https://fedoramagazine.org/use-the-dnf-local-plugin-to-speed-up-your-home-lab/

I saw the https://weldr.io/lorax/livemedia-creator.html#using-a-proxy-with-repos section of the documentation
and wondered whether the local plugin could somehow make this more simple.
I tried it and it did not work, but maybe I am doing something wrong.

I run the livemedia-creator in a VM with this command:
`livemedia-creator --ks ./${KS} --nomacboot --no-virt --anaconda-arg='--nosave=all' --make-iso --iso-only --iso-name Fedora-${FEDORA_VER}-x86_64.iso --project Fedora-Live --volid Fedora-${FEDORA_VER} --releasever ${FEDORA_VER} --resultdir /home/$USER/fedora-iso`
Installing the `python3-dnf-plugin-local` on the VM where the command is run does not cache the packages. They are downloaded each time the command is run:
```
...
2023-02-08 13:46:45,425: Running pre-installation tasks
2023-02-08 13:46:47,426: .
2023-02-08 13:46:47,426: Installing.
2023-02-08 13:46:47,426: Starting package installation process
2023-02-08 13:46:49,927: Downloading packages
2023-02-08 13:46:51,928: Downloading 1733 RPMs, 3.96 MiB / 1.78 GiB (0%) done.
2023-02-08 13:46:53,928: Downloading 1733 RPMs, 13.93 MiB / 1.78 GiB (0%) done.
...
```

**Comment by bcl** [comment]
Not currently, you would have to add the plugin to the dnf config that anaconda sets up, and that is independent from the host system, so installing the plugin isn't enough. I don't think there is any way to tell Anaconda to use it, but you might try asking them.
