### ISSUE TITLE
find kernel regex

### ISSUE THREAD

**Issue by kkzxak47** [weldr/lorax#1322]
In https://github.com/weldr/lorax/blob/00a97b6125eb94ebe90653d064155be0533567de/src/pylorax/treebuilder.py#L385
The "findkernels" function's regex is very strict with vmlinuz file name.
It cannot parse name like "vmlinuz-4.19.278-0004", I have to add a dot, for example by renaming kernel to "vmlinuz-4.19.278-0004.1" to make lorax to find my kernel.
Is it possible to support "vmlinuz-4.19.278-0004" as well?

**Comment by bcl** [comment]
No -- it needs to be able to parse out the arch and the flavor for use in other places, and the kernel naming here is tied pretty closely to that used by Fedora, CentOS, and RHEL.
eg. `vmlinuz-6.2.10-100.fc36.x86_64` or `vmlinuz-5.14.0-284.11.1.el9_2.x86_64+debug`
You should add `.DIST.ARCH` to be compatible.
