### ISSUE TITLE
Keep /usr/share/pixmaps/fedora-logo-sprite.svg in fedora boot.iso

### ISSUE THREAD

**Issue by KKoukiou** [weldr/lorax#1340]
The /usr/share/pixmaps/fedora-logo-sprite.svg file contains the best suitable logo for Web UI branding.

Looks like the /usr/share/pixmaps/fedora-logo-sprite.svg file from the fedora-logos package is present on Live media, but missing on boot.iso.

See https://github.com/rhinstaller/anaconda/pull/5046

**Comment by VladimirSlavik** [comment]
Ideally something like this would be possible in `runtime-cleanup.tmpl`:
```diff
- removefrom ${branding.logos} /usr/share/{kde4,pixmaps}/*
+ removefrom ${branding.logos} /usr/share/{kde4,pixmaps}/* --except /usr/share/pixmaps/fedora-logo-sprite.svg
```

However, the `--allbut` option does not do that, and `--except` does not exist.

I guess one could maneuver around this by being more specific, although it would not be pretty:
```diff
- removefrom ${branding.logos} /usr/share/{kde4,pixmaps}/*
+ removefrom ${branding.logos} /usr/share/kde4/*
+ removefrom ${branding.logos} /usr/share/pixmaps/bootloader/*
+ removefrom ${branding.logos} /usr/share/pixmaps/*.png
```
...which should trim it down to...
```
$ rpm -ql  fedora-logos | grep '/usr/share/pixmaps' | grep -v png | grep -v bootloader
/usr/share/pixmaps/fedora-logo-sprite.svg
/usr/share/pixmaps/fedora_whitelogo.svg
```

HTH?

**Comment by bcl** [comment]
I think that's the best we can do, other than leaving all of pixmaps in there (and that looks like it is about 3M so it's worth trying to trim it down).
