### ISSUE TITLE
Move packages needed by anaconda out of the template and into anaconda-install-env-deps

### ISSUE THREAD

**Issue by bcl** [weldr/lorax#1345]
Review what's being installed by templates, and what is needed by anaconda in various environments (eg. live vs. boot.iso) and move things into anaconda requirements.

**Comment by VladimirSlavik** [comment]
Thank you, wanted to file the exact same somewhere.

**Comment by bcl** [comment]
I think this is pretty stable these days? Closing it. Can reopen if needed.
