### ISSUE TITLE
treebuilder findkernels() only finds kernels in /boot

### ISSUE THREAD

**Issue by jlinton** [weldr/lorax#1350]
Systemd-boot systems (and maybe others) tend to put the kernels on the ESP to avoid needing a ext[234]/xfs/etc filesystem driver in EFI context/grub.

I guess findkernels() should also try calling grubby, which is a bit smarter (and shims via stubby/bootctl for systemd-boot) about just printing out the kernel/initrd data:

Ex:
#grubby --info ALL
title="Fedora Linux 39 (Workstation Edition Prerelease) (default) (selected)"
id="250bfee9fd43411a96d15d6d2da5d4a4-6.5.5-300.fc39.x86_64.conf"
kernel="/boot/efi//250bfee9fd43411a96d15d6d2da5d4a4/6.5.5-300.fc39.x86_64/linux"
initrd="/boot/efi//250bfee9fd43411a96d15d6d2da5d4a4/6.5.5-300.fc39.x86_64/initrd"
root="UUID=887de6b6-1720-473c-9f01-5ee6c4e0c801"
args="rhgb rd.auto=1 root=UUID=887de6b6-1720-473c-9f01-5ee6c4e0c801 systemd.machine_id=250bfee9fd43411a96d15d6d2da5d4a4 quiet"

or actual grubby:
index=0
kernel="/boot/vmlinuz-6.4.13-200.fc38.x86_64"
args="ro rhgb quiet initcall_blacklist=simpledrm_platform_driver_init rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1"
root="UUID=fcd106ff-477c-4750-9627-73e4ab9c503a"
initrd="/boot/initramfs-6.4.13-200.fc38.x86_64.img"
title="Fedora Linux (6.4.13-200.fc38.x86_64) 38 (Workstation Edition)"
id="fe10fbbff5ab40c7999956d403a202db-6.4.13-200.fc38.x86_64"

Although that said, running it from treebuilder, is problematic because bootctl can't find the ESP at the moment.

**Comment by bcl** [comment]
What are you working on? Is this for lorax or livemedia-creator? I can't think of a good reason to try to make systemd-boot ISOs, so maybe you are making disk images with lmc?
