### ISSUE TITLE
The live ISO images generated by livemedia-creator are unbootable if the squashed root filesystem is over 4GB

### ISSUE THREAD

**Issue by jkool702** [weldr/lorax#1353]
**Problem**: when generating a custom live ISO image, using the standard "squashfs root filesystem" method, if the squashed root filesystem is over 4 GB in size the live ISO will not be bootable. 

**Cause**: having a file larger than 4 GB necessitates having `/boot` be on a NTFS filesystem instead of a FAT32 filesystem, and the GRUB binary added to the ESP does not have NTFS support. If a grub NTFS module is being added, then it is getting added to the NTFS `/boot` partition where it doesnt do any good. Unfortunately, the kernel/initramfs (which has ntfs support compiled in) is *also* on the NTFS `/boot` partition. Ultimately, this means that when you try to boot an image that (by necessity) has a NTFS `/boot` partition you get dropped into a GRUB recovery shell where you cant do anything because there is nothing on the ESP that GRUB can utalize to read that NTFS partition.

**Possible Solutions**: It seems like there are 2-3 fairly obvious possible solutions to this:

1. Make it so that GRUB can read data on a NTFS filesystem (in a way that doesnt require "accessing something on a NTFS filesystem" as a prerequisite). I'd imagine this involves either a) adding the GRUB NTFS module to the ESP and adding `insmod ntfs` to the GRUB menu) or b) compiling GRUB NTFS support into the grub EFI image on the ESP.
2. Move the kernel and initramfs onto a FAT32 partition (the ESP seems like it would be the obvious choice, though adding another `/boot`-esque partition for it could work too), while keeping the squashfs root filesystem image on the NTFS `/boot` partition. This would also require ensuring that the kernel has ntfs support compiled in and perhaps modifying/adding a dracut routine that tells the kernel to mount the NTFS `/boot` partition to find the squashfs root filesystem image.
3. Im not sure if this would work, but perhaps replacing the grub efi (e.g., at /boot/EFI/BOOT/BOOTX64.EFI) with a unified kernel image (that has the same name and has NTFS support compiled in and knows it needs to mount the NTFS `/boot` partition to find the squashfs root filesystem image).

**Comment by bcl** [comment]
Can you describe what you are doing in a bit more detail and maybe include relevant logs from trying to boot? In the live iso the UEFI binaries are on the iso under `/EFI`, and in the embedded `efiboot.img` so booting them shouldn't have anything to do with the size of the squashfs.img . The squashfs image is then mounted by the initramfs and at that point there should be no FAT32 involved. If the squashfs.img is > 4G the iso should be building with `-iso-level 3` in order to support larger files, maybe what you are seeing is related to that?
