### ISSUE TITLE
RFE: support a feature to read external file for templating

### ISSUE THREAD

**Issue by tagoh** [weldr/lorax#1363]
In Fedora 39, We have implemented [default-fonts](https://fedoraproject.org/wiki/Changes/ImproveDefaultFontHandling) meta packages to simplify the package installation for default fonts. We don't need to update lorax template files anymore when changing our default fonts. However, lorax still have a hardcoded packages/files to clean up unnecessary files. This doesn't effectively work on meta packages because there are no way to know the real package name from them.

To improve this, I want to propose a feature in lorax to read a sort of manifest file in the package to describe what files are needed (or to drop; dunno which one is better yet from POV of the security risks) and then process instead of the hardcoded files in a template.

For font package side, I'm not supposed to create that file by hand (for font packages at least). We basically rely on fonts-rpm-macros to generate most of things in a spec file.  So it could be done by rebuilding fonts packages once the necessary changes is landed in fonts-rpm-macros.

Also, I want to bring this to coming Fedora Changes proposal when it is ready.

How does it sound?

**Comment by tagoh** [comment]
We can't promise anything about it. It may happens or may not. I didn't check but there may be more  files we can drop. dunno.

**Comment by juhp** [comment]
> removefrom google-noto-sans-cjk-fonts /usr/share/fonts/google-noto-sans-cjk-fonts/NotoSansCJK-{Black,Bold,*Light,Medium,Thin}.ttc

If we switch lorax to use the noto vf cjk fonts - this should no longer be needed

**Comment by juhp** [comment]
I think we can switch lorax to the default-fonts metapackages first in line with the rest of the Fedora
and see if there are any more extra fonts appearing. If it is just NotoSans-Italic-VF.ttf, it might be overkill to do more,
though I also like the idea of having a such a non-minimal manifest file in the fonts packages,
of course that would also have to be kept up to date too...
