### ISSUE TITLE
mkksiso doesn't support EUFI entries

### ISSUE THREAD

**Issue by jkonecny12** [weldr/lorax#1411]
Hello, UEFI is more and more important these days and mkksiso should support these with the `-r` and `-c` options for adjusting UEFI entries.

**Comment by bcl** [comment]
Please be more specific. `mkksiso` should work with EFI, it edits all the configs and rebuilds the efi image, but needs to be run as root to be able to do that. Maybe that's what you are seeing?

**Comment by jkonecny12** [comment]
Seems that this was issue between chair and monitor. Not sure what I did wrong but it works now. Sorry for the noise.
