### ISSUE TITLE
Investigate rpm-ostree for ISO

### ISSUE THREAD

**Issue by cgwalters** [weldr/lorax#143]
When generating ISO-with-content-embedded, as we're doing for Atomic Host and I am doing for [workstationostree](https://pagure.io/fork/walters/workstation-ostree-config/commits/f24-continuous), currently there's lots of duplicate files between the ISO and the data.

This isn't easily fixable with ISO + traditional RPM, but with ostree, if we had an ostree commit for the ISO data, then all we'd need to do is set the content repo to use it as a parent, and everything should be transparently dedup'd.

This would be most of a win for the desktop case since the content already has a desktop.  For the AH case I'd expect only a small space increase over the anaconda base.

**Comment by cgwalters** [comment]
Of course though for desktops, it's more common to do Live installs where it's all fairly dedup'd since `anaconda` is just another package in the set.   So another approach would be to try to do that somehow for the server case too.  It's like [CoreOS](https://coreos.com/) works - their installer is just a script that you can run from a live system.  The full generalization of this is having the installer in a (privileged) container, although I can imagine that'd be a lot of work from where we are now.

**Comment by bcl** [comment]
Interesting idea, it would be pretty useful if you wanted to provide a number of installation options built on a base system. Maybe a live ostree image with an anaconda addon to select the commit to use.

**Comment by cgwalters** [comment]
See also https://pagure.io/fedora-atomic/issue/32

**Comment by bcl** [comment]
Currently no time to implement this :)
