### ISSUE TITLE
Template improvements

### ISSUE THREAD

**Issue by jaymzh** [weldr/lorax#148]
Problem: We have changes we want to make to templates, but we don't want to fully fork them and then loose upstream changes.

Proposed solutions:
1. `templates.d/` is already built for multiple directories. It would be great if they stacked. In order. So `1-site-early/runtime-postinstall.tmpl` happened before `99-generic/runtime-postinstall.tmpl` which happened before `100-site-late/runtime-postinstall.tmpl`. This would give great access to leverage the existing templates while also extending them.
2. If that's not desirable and "one overrides the other" is really important, the default templates could have an `include` syntax that included other files, if they were present, at specific points providing "hook points" for people to hook into them.

**Comment by bcl** [comment]
One problem with breaking them up into smaller pieces will be passing variables between them, and more places to look when you need to change something. Building a whole hierarchy of templates is going to overly complicate things. I think forking is probably the best thing to do -- they're pretty stable so tracking upstream shouldn't be too hard. We already have an example of including others with the --add-template option, but that won't override anything, just add new ones.
