### ISSUE TITLE
Unclear options descriptions in docs

### ISSUE THREAD

**Issue by Frodox** [weldr/lorax#155]
There are some problem with chars. For example https://rhinstaller.github.io/lorax/pylorax.html#pylorax.ltmpl.LoraxTemplateRunner.installpkg

here is line
`installpkg [–required] [–except PKGGLOB [–except PKGGLOB ...]] PKGGLOB [PKGGLOB ...]`
which is wrong, because symbols `--` (in [source](https://rhinstaller.github.io/lorax/_modules/pylorax/ltmpl.html#LoraxTemplateRunner.installpkg)) should not be replace with `–`.

So, developer needs to go in [`source`](https://rhinstaller.github.io/lorax/_modules/pylorax/ltmpl.html#LoraxTemplateRunner.installpkg) to know, should he use `-` or `--` :)

**Comment by bcl** [comment]
I think all of those examples need to be wrapped in 2 backticks to keep sphinx from changing them.

**Comment by bofh80** [comment]
This appears to be hosted here now: http://weldr.io/lorax/_modules/pylorax/ltmpl.html

And displays correctly afaict. Something else needs done that i'm not seeing?

**Comment by bofh80** [comment]
http://weldr.io/lorax/pylorax.html  rather it's here and still needs fixed.

**Comment by bofh80** [comment]
Ok so it seems there might be two ways of fixing this.
Either enable smart quotes in sphinx
or possibly:
-//-
instead of --

**Comment by bcl** [comment]
Adding `smartquotes=False` to docs/conf.py fixes it.
