### ISSUE TITLE
boot.iso has no metadata inside

### ISSUE THREAD

**Issue by lubomir** [weldr/lorax#187]
If you go to https://getfedora.org and download a netinst image (which is just renamed boot.iso), there is pretty much no way other than parsing a filename to figure out what it is (for example what architecture the image is for).

Lorax generates `.discinfo` and `.treeinfo` files together with the iso, but does not include them in the image. These files are only available in the lorax output dir.

Do you think it would make sense to put them inside the boot.iso itself?

**Comment by bcl** [comment]
Hrm, interesting. I expected .discinfo to make it into the boot.iso, but it doesn't. I think it should, but we'd need to make sure that doesn't confuse anything (eg. anaconda looks for .treeinfo to see if it is a dvd). It doesn't appear to care if .discinfo is there, but something else might.

@ausil probably knows if this would be safe.

**Comment by Frodox** [comment]
Yip, there is definetly should be `.treeinfo` and `.discinfo` inside `.iso`. Yup, anaconda wouldn't work without that. I've already faced with that during creating custom RH-based distro and currently I need to manually copy this files from lorax's output dir.

**Comment by bcl** [comment]
@Frodox not .treeinfo, that's for places with the package tree, like the DVD or the https repos.

**Comment by ausil** [comment]
@bcl I am not aware of anything that would break with .discinfo inside the iso
