### ISSUE TITLE
--excludepkgs was used by rpm-ostree-toolbox

### ISSUE THREAD

**Issue by cgwalters** [weldr/lorax#25]
Regression from: https://github.com/rhinstaller/lorax/commit/431ca6cea47d1721ac2982fa947e7a9aa388a9ca

We could probably avoid using exlcudepkgs now...but just a note that it is supported at least by the lower levels (hawkey/libsolv), see https://github.com/hughsie/libhif/pull/26 which changed libhif to support it.

**Comment by bcl** [comment]
Right, dnf's exclude support is different than yum's. IIRC the way it works is that the exclude applies to everything, not just to a specific repo, but I should revisit this for F23 to see if there is anything worth implementing.
