### ISSUE TITLE
fill_sack not reloading repositories and failing on setting includes/excludes

### ISSUE THREAD

**Issue by marcoguerri** [weldr/lorax#254]
Hi,

I am having some issues on this control path:

https://github.com/rhinstaller/lorax/blob/d93adc283fae671d697b933661be39f65c315952/src/pylorax/ltmpl.py#L648-L650

I am invoking lorax cli with a repo definition that contains an `includepkgs` directive (the repo definition is passed via the `--repo` flag). This results in the following stack trace:
```
2017-10-06 11:24:34,410:   run_pkg_transaction
  run_pkg_transaction
2017-10-06 11:24:34,411:   ValueError: Can't set use_includes for repo with given name.
  ValueError: Can't set use_includes for repo with given name.
Traceback (most recent call last):
  File "/usr/sbin/lorax", line 279, in <module>
    main()
  File "/usr/sbin/lorax", line 135, in main
    remove_temp=True, verify=opts.verify)
  File "/usr/lib/python3.6/site-packages/pylorax/__init__.py", line 280, in run
    rb.install()
  File "/usr/lib/python3.6/site-packages/pylorax/treebuilder.py", line 122, in install
    self._runner.run("runtime-install.tmpl")
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 220, in run
    self._run(commands)
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 239, in _run
    f(*args)
  File "/usr/lib/python3.6/site-packages/pylorax/ltmpl.py", line 650, in run_pkg_transaction
    self.dbo.fill_sack(load_system_repo=True, load_available_repos=False)
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 347, in fill_sack
    self._setup_excludes_includes()
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 157, in _setup_excludes_includes
    self.sack.set_use_includes(True, r.id)
ValueError: Can't set use_includes for repo with given name.
```
This comes from libdnf, which attempts to iterate over all the repos defined in the `sack` object and raises [when it cannot find a match](https://github.com/rpm-software-management/libdnf/blob/262bdacb650b707d61f13e51aaaf8d4c83844b81/python/hawkey/sack-py.c#L542-L545). It appears that recently `dnf` library switched to using a new interface exposed by `libdnf` (i.e. `set_use_includes` method of the sack object). Specifically, it happened [here](https://github.com/rpm-software-management/dnf/commit/4c4616ff6a2b5847fb70ce2e0f8414c1f728b9c1#diff-4877e5828297060c14b3107f32dcfff8). Now, my understanding is that `fill_sack` creates [a brand new `sack`](https://github.com/rpm-software-management/dnf/blob/4c4616ff6a2b5847fb70ce2e0f8414c1f728b9c1/dnf/base.py#L300) and as a consequence all the repo definitions are lost. Not forcing the reload of all repositories via `load_available_repos` (in addition to the systems ones) makes that code path blow up on `set_use_includes` (actually further down in the libdnf C import module). I do not have a complete understanding of why it used to work before switching to the new interface. It seems that `add_includes` was following a control path that did not depend on having the repositories defined ([ending up here](https://github.com/rpm-software-management/hawkey/blob/master/src/sack.c#L864-L875)).

What I can tell is that `s/load_available_repos=False/load_available_repos=True/` seems to fix this issue.

As a side question, I wonder what 
```
self.dbo.reset(repos=False) 
```
is supposed to do? All the actions in that [function](https://github.com/rpm-software-management/dnf/blob/5de9bd300956a2e8e128951b45de3520f6418949/dnf/base.py#L414-L427) are gated by flags that are False by default.

Could you please have a look at that usage of `self.dbo.fill_sack`?

**Comment by bcl** [comment]
Which version of lorax are your using, and what version of dnf do you have installed?

**Comment by marcoguerri** [comment]
Right, important detail. I am invoking lorax in a rawhide chroot, so

- lorax-27.11-1.fc28.x86_64.rpm
- dnf-2.7.3-1.fc28.noarch
- libdnf-0.10.1-2.fc28.x86_64
- python3-hawkey-0.10.1-2.fc28.x86_64

**Comment by marcoguerri** [comment]
Adding some more hopefully useful information: you can reproduce the failure with https://gist.github.com/marcoguerri/2562170891b8a05b337247f111c68d53.

**Comment by bcl** [comment]
> Adding some more hopefully useful information: you can reproduce the failure with these commands

Unrelated to this bug, but you're going to need to run mock --old-chroot to make sure the loop devices are setup correctly.

**Comment by bcl** [comment]
I modified your script slightly and it works fine for me running it on F27. I dropped running mock with sudo, you should add yourself to the mock group instead. Weird things can happen when using mock as root. I added --old-chroot to the mock command. And I set SELinux to permissive. The script ran fine.
