### ISSUE TITLE
Move from genisoimage to xorriso

### ISSUE THREAD

**Issue by Conan-Kudo** [weldr/lorax#326]
`genisoimage` (from `cdrkit`) is old and unmaintained. These days, the modern replacement available is from [`xorriso`](https://www.gnu.org/software/xorriso/), which looks like it supports all the features that exist in our variant of `genisoimage`.

Please switch from `genisoimage` to `xorriso`.

**Comment by bcl** [comment]
Currently xorrisofs isn't ready, I'm still hitting a problem with isohybrid not recognizing how it writes the mac boot image into the iso.

**Comment by Conan-Kudo** [comment]
@bcl You don't need to do separate isohybrid. `xorriso` can do hybridization itself.

**Comment by bcl** [comment]
I found this - https://www.syslinux.org/wiki/index.php?title=Isohybrid
But the created iso doesn't boot correctly. I'll have to look into this when I have more time.

**Comment by bcl** [comment]
https://github.com/bcl/lorax/tree/master-xorriso

**Comment by Conan-Kudo** [comment]
I think @schaefi recently had to resolve something similar in KIWI, he might have an idea...

**Comment by schaefi** [comment]
yes and with the help of Mr. awesome Thomas Schmitt <scdbackup@gmx.net> :smiley: 

You can find my xorriso coding here

* https://github.com/SUSE/kiwi/blob/master/kiwi/iso_tools/xorriso.py

The hybrid code to boot the iso as disk is implemented by using isohdpfx.bin from syslinux. You need a reasonable new syslinux version, but I guess that's not a problem

If you also plan to support efi it's required to create fat embedded efi image

* https://github.com/SUSE/kiwi/blob/master/kiwi/bootloader/config/grub2.py#L569

Hope that helps to get you started. Moving away from cdrtools is really worth the effort

**Comment by Conan-Kudo** [comment]
So I've completed the move to xorriso for livecd-tools and released v26 with it.

Here's the diff of my changes needed to do it: https://github.com/livecd-tools/livecd-tools/compare/4412b55ed2eb6db1180933701b66d7ae4a7fcbd3...320d92a8cdb692f704ce83895bd921450522e946

**Comment by Conan-Kudo** [comment]
@bcl Any luck on this? It'd be good to have lorax switched over for EL8 and Fedora, since xorriso is actively maintained...

**Comment by Conan-Kudo** [comment]
@bcl It looks like this is now done for `master`, can we have this also done for `rhel8-branch` too?

**Comment by bcl** [comment]
> @bcl It looks like this is now done for `master`, can we have this also done for `rhel8-branch` too?

No, this level of change isn't appropriate for the rhel8-branch

**Comment by Conan-Kudo** [comment]
@bcl I guess that's up to you if you want to maintain cdrkit with no upstream and weird patches for 10+ more years...

As far as I know, it's the only thing that actually explicitly requires cdrkit over any mkisofs implementation, and xorriso is actively maintained through the libburnia project.

If I were you, I'd go ahead and do the switch now while RHEL8 is not GA...

**Comment by bcl** [comment]
We're actually already using this, it provides a compatibility mode for mkisofs

**Comment by Conan-Kudo** [comment]
@bcl The issue is that some of the extended switches for EFI (among other things) aren't identical between genisoimage and xorrisofs, which is why I switched to calling genisoimage in livecd-tools (https://github.com/livecd-tools/livecd-tools/commit/dbd94def9c102b7cd643ead6af15922774d2d0d9) and then later switched to xorrisofs (https://github.com/livecd-tools/livecd-tools/commit/686e5b63111ba40319c7a42d0ec966260d43d2a9).

Since we don't care about cdrtools compatibility (since cdrtools is not present in RH/Fedora), I just went ahead and swapped over. 

Honestly, I suggest you do the same.

**Comment by schaefi** [comment]
> If I were you, I'd go ahead and do the switch now while RHEL8 is not GA...

I would also encourage people to do this switch. maintaining cdrkit is a painful thing to do, not only from the bits and bytes perspective ;) Just in case you need another developer opinion, it was really worth the switch when I did it in kiwi and Thomas Schmitt is a brilliant guy to talk to

**Comment by bcl** [comment]
Closing this, it is now in rawhide in lorax-30.14-1
