### ISSUE TITLE
lorax does not use comps arch filtering

### ISSUE THREAD

**Issue by AdamWill** [weldr/lorax#336]
comps allows syntax like this:

      <packagereq type="mandatory" arch="i386,x86_64">grub2-pc</packagereq>

to signify that a package should only be included on particular arches. However, you have to do something specific to actually make this take effect: when calling the dnf Base instance's `read_comps` method, you have to set `arch_filter=True`. The patch would be this:

    --- a/src/sbin/lorax
    +++ b/src/sbin/lorax
    @@ -270,7 +270,7 @@ def get_dnf_base_object(installroot, sources, mirrorlists=None, repos=None,
                 log.info("Disabled repo %s", r)
     
         dnfbase.fill_sack(load_system_repo=False)
    -    dnfbase.read_comps()
    +    dnfbase.read_comps(arch_filter=True)
     
         return dnfbase
     
I'm filing this as an issue rather than a PR as we should probably kick around the consequences of doing it a bit. The *reason* to do it would be to let us make comps fully correct: without this mechanism we cannot list precisely the packages required in each comps group, without any *non-existent* packages, because some packages are essential on one arch but do not exist on another (bootloader packages are a good example). If we ever want to make composes fail on a group package not existing again (which seems like a good idea at least in theory), we need this.

However, there *could* be unexpected consequences. The arch actually used to filter comps with would be the dnf basearch; we'd have to consider whether there are any cases where we might actually wind up filtering by the *wrong* basearch (e.g. if we're running lorax to produce an i686 install tree on an x86_64 system, or something), and if so, can this be addressed.

Another question wrt lorax specifically is whether this would matter *at all*; I'm not sure whether lorax actually does anything much with comps any more.

The same situation exists in anaconda, and I'll file a similar ticket there for discussion.

**Comment by bcl** [comment]
I don't think this would matter, unless dnf is doing something behind the scenes. All the packages are selected via dbo.install()

**Comment by AdamWill** [comment]
I suppose it might matter if we ever had a group or env group specified in the templates by `@` syntax...dunno if that even works, though?

**Comment by bcl** [comment]
Currently you cannot install groups or environments, so I'm going to close this until we decide that's something we want to start doing.
