### ISSUE TITLE
livemedia-creator: include .buildstamp in live images

### ISSUE THREAD

**Issue by AdamWill** [weldr/lorax#350]
In Fedora 28+ - basically since the install classes were moved into anaconda itself ([here's the Workstation migration for e.g.](https://github.com/rhinstaller/anaconda/commit/c27121a89840716287febd30069849496693617c#diff-79360e9268c172e8c5371776b86cc6d3)), the Workstation install class is currently not correctly used on live images. As discussed in [this PR](https://github.com/rhinstaller/anaconda/pull/1441), the best fix for this would probably be for livemedia-creator to include the `.buildstamp` file in live images; this should allow anaconda to detect the variant correctly with its existing code that's used for non-live scenarios. For F28 we're probably going to land an extra bit of detection code in `liveinst` to fix this temporarily, but going forward it would probably be a good idea to do a more correct permanent fix.

@poncovka @M4rtinK

**Comment by bcl** [comment]
I think your Anaconda PR (https://github.com/rhinstaller/anaconda/pull/1448) is the best way to handle this for now (or maybe something in the kickstarts). .buildstamp lives inside the rootfs, and lmc doesn't really have anything to do with that, it's all installed by Anaconda when building the image. lmc also doesn't currently have the --variant cmdline arg so it wouldn't be able to create a correct .buildstamp without more changes, and changes in how it is called.

**Comment by AdamWill** [comment]
I dunno, it seems pretty icky to me - it only handles Workstation, after all, if we actually had more install classes it'd wind up as an ugly conditional forest pretty fast. It does seem cleaner to me for it to happen from 'the other end'...

**Comment by bcl** [comment]
Sure, but the other end doesn't know any more than anaconda does.
