### ISSUE TITLE
/api/status provides inconsistent results between backends

### ISSUE THREAD

**Issue by atodorov** [weldr/lorax#355]
This is what bdcs-api-server provides:
```
{"supported":true,"schema":4,"backend":"weldr","version":"44c1354","db":4}
```

This is what lorax-composer provides:
```
{
  "api": "0", 
  "backend": "lorax-composer", 
  "build": "19.7.14-1", 
  "db_supported": true, 
  "db_version": "0", 
  "schema_version": "0"
}
```

The only common key is `backend`. Looks like `build` is the same as `version`, `db_supported` is probably the counterpart of `supported` and `db_version`/`schema_version` should be `schema`. 

@bcl a few questions:

1) How do I know when the backend is ready (e.g. refreshed yum repos) ? Currently I grep for `"supported":true` (including the quotes and lack of white space).

2) Is `db_supported: true` / `supported: true` equivalent to "I'm up and running and ready to serve requests" ?

3) lorax-composer takes couple of minutes to fetch yum metadata and before that it doesn't appear to be responding to http requests. Can we make it to respond with a not-ready status/response instead of timing out? 

For the record this needs to be resolved before I can continue with tests against lorax-composer.

**Comment by bcl** [comment]
Sorry about that. I think we should go with the lorax-composer version, and I'll update the bdcs-api at some point. The API won't respond until the metadata is updated, so any kind of response means it is ready.

The db_supported field will always be true for lorax-composer, for bdcs-api it means that the metadata.db schema matches what the API expects. This can be used to debug problems with using an older metadata.db with a newer bdcs-api version.

I don't want to fire up the API until the metadata has been fetched. That would involve locking things like depsolve and I don't think it's worth the extra complexity.

**Comment by atodorov** [comment]
So in this case a grep for db_supported: true is just fine for me, only need to unify the syntax.

Do you want me to open an issue with bdcs-api to adjust the JSON response there?

**Comment by bcl** [comment]
> Do you want me to open an issue with bdcs-api to adjust the JSON response there?

Sure, that way we don't lose track of it.
