### ISSUE TITLE
Live image sizing does not seem to account for additional template copy actions.

### ISSUE THREAD

**Issue by integerbasic** [weldr/lorax#384]
Using an additional template to stage an ostree into the Live image;
runcmd ostree --repo=${root}/ostree/repo pull --mirror ${ostree_osname} ${ostree_install_ref}

Results in a failure due to a full image:
cp: error writing '/var/tmp/lorax.imgutils.05NN7k/./ostree/repo/summary': No space left on device
cp: failed to extend '/var/tmp/lorax.imgutils.05NN7k/./ostree/repo/summary': No space left on device

This pattern is from some published Fedora source so perhaps this problem is version specific.  I am using Centos 7.5. Or perhaps I misunderstand the model.  Maybe there is a way to configure the desired Live image filesystem size?

**Comment by bcl** [comment]
The size of the filesystem is controlled by the part / ... command in the kickstart. If you are including more content than Fedora then you will need to make it larger.

**Comment by integerbasic** [comment]
hmm.  I understand how I could do that if I were using 'livemedia-creator', since it does take a kickstart file as an input.  But I am using 'lorax' directly, like so:

DIR_OUT="./results"
echo "Output directory is : $DIR_OUT"

sudo lorax -p Myspin -v 7 -r 4 \
    --repo CentOS-Base.repo \
    --repo CentOS-updates.repo \
    --repo CentOS-extras.repo \
    --repo CentOS-atomic.repo \
    --add-template=$PWD/ostree-based-installer/lorax-configure-repo.tmpl \
    --add-template=$PWD/ostree-based-installer/lorax-embed-repo.tmpl \
    --add-template-var=ostree_install_repo=http://localhost:8000/ostree/ \
    --add-template-var=ostree_update_repo=http://localhost:8000/ostree/ \
    --add-template-var=ostree_osname=myspin \
    --add-template-var=ostree_install_ref=myspin-base/dev \
    --add-template-var=ostree_update_ref=myspin-base/dev \
    $DIR_OUT

This works if I hack the treebuilder.py module like so:
< 159    def create_runtime(self, outfile="/var/tmp/squashfs.img", compression="xz", compressargs=[], size=2):
> 159    def create_runtime(self, outfile="/var/tmp/squashfs.img", compression="xz", compressargs=[], size=4):

But I'm looking for the proper approach.
Thank you for your previous response; I appreciate any additional suggestions.

**Comment by integerbasic** [comment]
Here is a theory;
1- I am trying to create a boot ISO for a customization of **Centos 7 Atomic**
2- To do this, the proper context for running 'lorax' is also **Centos 7 Atomic**
3- I am running 'lorax' in **Centos 7**
4- This mismatch is not going to work

The reason I even tried this is because there doesn't seem to be an easy way _within_ **Centos 7 Atomic** to install all the development and distribution tools (such as lorax).  But perhaps that is the direction I need to pursue.

**Comment by bcl** [comment]
Upstream we have `--rootfs-size`, if you want us to backport this to RHEL7 please open a bug against lorax on https://bugzilla.redhat.com
