### ISSUE TITLE
livemedia-creator: virt-uefi -> dracut: cannot boot image

### ISSUE THREAD

**Issue by doverride** [weldr/lorax#394]
I am trying to get --virt-uefi to work but i have difficulties:

Without --virt-uefi things work fine. I use this ks:
https://raw.githubusercontent.com/DefenSec/dssp2-standard/master/support/scripts/livemedia_creator.ks

If I add: `part /boot/efi --size 200 --fstype efi` and run livemedia-creator with --virt-uefi then dracut hangs because the `network --device=link` causes issues. Changing -to `-device=ens3` *seems* to get me a network but dracut still returns " cannot boot image" and drops me to a shell.

Is --virt-uefi currently working for you? If so, do you have any idea what i should do to make it work?

**Comment by bcl** [comment]
You don't need to use --virt-uefi to make a UEFI bootable livecd, livemedia-creator will set that up for you when it wraps the rootfs with the iso. Make sure you start with the example kickstart - https://github.com/weldr/lorax/blob/master/docs/fedora-livemedia.ks and then modify with your additions. I notice that you don't have a grub2-efi package listed which will make it fail to setup the iso correctly.

**Comment by bcl** [comment]
No, for a live iso it doesn't matter. We just drop in the needed files and the UEFI system figures it out.
So if it isn't working there is some other reason for it. Check the logs for lorax, and you can look at the output of dumpet -i <path to iso> which should contain at least one section with: PlatformId: 0xef (EFI) in it.

**Comment by doverride** [comment]
it seems to install something in /boot/efi/EFI/fedora but theres no /boot/efi/EFI/boot

Testing further...

BTW your ks files lack "fedora-logos" in %packages which makes things fail

**Comment by doverride** [comment]
Got a step further, by installing "shim" i now have two files in /boot/efi/EFI/BOOT

still doesnt boot in efi mode though

**Comment by doverride** [comment]
I think (hope) i may have figured it out. For some reason installing grub2-efi defaults to grub2-efi-ia32 instead of grub2-efi-x64

Now trying with explicitly specifying grub2-efi-x64

**Comment by doverride** [comment]
ok almost there. This endeavour requires grub2-efi-x64-cdboot

**Comment by doverride** [comment]
got uefi to "work", should secure boot work? because i cannot get it to boot with secure mode enabled

**Comment by doverride** [comment]
It is strange to me. When i set secure boot in the "bios", then I am able to boot the LiveCD, but the kernel say's that security boot is not enabled.

**Comment by bcl** [comment]
I've tested the xorriso PR with SB enabled, and it does boot just fine so I'm going to close this one.
https://github.com/weldr/lorax/pull/572
