### ISSUE TITLE
Return error ids from API calls

### ISSUE THREAD

**Issue by larskarlitski** [weldr/lorax#414]
A lot of endpoints return an `error` key in the response on failure. These contain a human readable string (or strings, when multiple errors are returned). weldr-web often needs to be able to differentiate between different errors, especially when part of the API URL is passed in from user input. It's hacky and brittle to do this by parsing the human-readable strings.

A possible solution is to change error strings to be objects with a documented error id:

```json
"error": {
    "id": "BlueprintNotFound",
    "parameters": {
        "blueprint": "foo"
    }
}
```

I don't think we need a human-readable message at all in this case.

Endpoints where this is an issue for weldr-web right now:
- modules/info
- blueprints/info
- blueprints/diff (incorrect blueprint or incorrect commit)
- projects/source/info
- compose (any of the parameters passed in the POST data might be wrong)
- compose/status (does not return any error right now)

**Comment by bcl** [comment]
I think we need both. The API knows what the error is, and should describe it for humans and add an id for the UI. If we only provide IDs then the knowledge about what an error id means will need to be maintained and kept in sync in multiple places.
We need to be careful not to make this too complex. I don't thing we need to include the params as you show there, the caller knows what they passed in.

**Comment by clumens** [comment]
I'm curious if there needs to be any namespacing to these IDs, or some sort of standard for how they should be named, or what.  I don't want to just start slapping names around and they end up being unhelpful.

**Comment by clumens** [comment]
WIP:  https://github.com/clumens/lorax/tree/error-id

**Comment by clumens** [comment]
And pushed.  See src/pylorax/api/errors.py for the possibilities, and let me know if anything needs to be modified or changed.
