### ISSUE TITLE
Composer depsolve error on RHEL 7.6 in Beaker

### ISSUE THREAD

**Issue by atodorov** [weldr/lorax#435]
```
# composer-cli compose start http-server tar

2018-08-17 09:35:11,555: Problem depsolving http-server: There was a problem depsolving [(u'httpd', u'2.4.*'), (u'mod_auth_kerb', u'5.4'), (u'mod_ssl', u'2.4.*'), (u'openssh-server', u'7.*'), (u'php', u'5.4.*'), (u'php-mysql', u'5.4.*'), (u'rsync', u'3.1.*'), (u'tmux', u'1.8')]: Package tuple ('restraint-rhts', 'x86_64', '0', '0.1.35', '1.el7bkr') could not be found in rpmdb
```

I have installed composer-cli and lorax-composer on RHEL 7.6 system, not modified any of the blueprints.

**Comment by bcl** [comment]
This is not a composer bug, it's something related to the available packages in the environment.

**Comment by atodorov** [comment]
This is a composer bug IMO. On another, freshly installed system I did:

```
# rm /etc/yum.repos.d/beaker-harness.repo  (this is where restraint-rhts comes from I think)
# rm /etc/yum.repos.d/beaker-tasks.repo
# yum clean all
# composer-cli compose start http-server tar
Compose 72f0052d-b2a6-4c70-aea1-1abcf3cf3cc8 added to the queue
```

**Comment by bcl** [comment]
I don't see how this is a composer bug, if depsolving isn't working it's either yum or a repo problem. Especially if it works when removing the repo.

**Comment by atodorov** [comment]
OK, so restraint-rhts depends on rhts-python which conflicts with rhts-test-env, which is pre-installed on the system. However none of these packages is used in the http server recipe so why do I get an error ?

**Comment by bcl** [comment]
Something must be pulling it in as a dependency.

**Comment by atodorov** [comment]
Works for me now. More info in https://bugzilla.redhat.com/show_bug.cgi?id=1625242
