### ISSUE TITLE
The copy of simpleconfig that was taken from pyanaconda still needs other bits of pyanaconda

### ISSUE THREAD

**Issue by AdamWill** [weldr/lorax#449]
https://github.com/weldr/lorax/commit/4d9ef60460f64b7b9f85e0c46fea1d69bf3f2e3e seems to have intended to take `simpleconfig` from pyanaconda and just dump it into lorax wholesale so lorax can use it without actually requiring `pyanaconda`, but...that doesn't really work, because this:

    from pyanaconda.core.util import upperASCII

so if you actually try and run current lorax in an environment without anaconda-core installed, [it just blows up](https://pagure.io/dusty/failed-composes/issue/716):

    DEBUG util.py:439:  Traceback (most recent call last):
    DEBUG util.py:439:    File "/usr/sbin/lorax", line 38, in <module>
    DEBUG util.py:439:      from pylorax.simpleconfig import SimpleConfigFile
    DEBUG util.py:439:    File "/usr/lib/python3.7/site-packages/pylorax/simpleconfig.py", line 24, in <module>
    DEBUG util.py:439:      from pyanaconda.core.util import upperASCII
    DEBUG util.py:439:  ModuleNotFoundError: No module named 'pyanaconda'

You *can* just take `upperASCII` and all the other bits of `pyanaconda.core.util` that are needed to back  it and dump them in the top of `pylorax/simpleconfig.py` to make it work, but that seems kinda...inelegant.

This is currently blocking Rawhide and F29 composes.

**Comment by AdamWill** [comment]
https://stackoverflow.com/questions/2819696/parsing-properties-file-in-python/25493615#25493615 suggests a way to use python's own `configparser` (which lorax already uses in other places) to read files like this (ones that look more or less like .ini files, but have no section headers) by using a simple wrapper to add a dummy section header. That seems like a sane solution to me.

**Comment by ferdnyc** [comment]
> You can just take upperASCII and all the other bits of pyanaconda.core.util that are needed to back it and dump them in the top of pylorax/simpleconfig.py to make it work, but that seems kinda...inelegant.

It did seem inelegant, but also fairly straightforward, so #452 contains a change which does just that, as an alternative solution. (It's really not that many bits, just three simple functions and the `_upperASCII_table`.)

I suspect #451 is the better solution, though.
