### ISSUE TITLE
lorax both has a copy of pyanaconda's simpleconfig...and imports it (without the package depending on it)

### ISSUE THREAD

**Issue by AdamWill** [weldr/lorax#450]
As noted in https://github.com/weldr/lorax/issues/449 , https://github.com/weldr/lorax/commit/4d9ef60460f64b7b9f85e0c46fea1d69bf3f2e3e stuffed a copy of pyanaconda's `simpleconfig` into lorax (only it doesn't really work). However, another bit of lorax actually [imports it from pyanaconda](https://github.com/weldr/lorax/blob/b1e2bbfd17e7c9206837738230b4ee824ccff110/src/pylorax/api/compose.py#L43):

    from pyanaconda.simpleconfig import SimpleConfigFile

however, the RPM spec does not depend on anaconda-core despite using it in this way.

It seems that this codepah is not actually hit during Fedora composes, because if it was I'd expect them to blow up due to pyanaconda not being available. But there clearly seems to be an inconsistency here - it doesn't seem to make sense for one part of lorax to import simpleconfig from pyanaconda, and another part to use a local copy of it.

**Comment by ferdnyc** [comment]
That line is in a file that's part of lorax-composer, which (according to [the spec file](https://github.com/weldr/lorax/blob/b1e2bbfd17e7c9206837738230b4ee824ccff110/lorax.spec)) does have anaconda-tui as a dependency.

(Lines 121-139:)
```specfile
%package composer
Summary: Lorax Image Composer API Server
# For Sphinx documentation build
BuildRequires: python3-flask python3-gobject libgit2-glib python3-pytoml python3-semantic_version

Requires: lorax = %{version}-%{release}
Requires(pre): /usr/bin/getent
Requires(pre): /usr/sbin/groupadd
Requires(pre): /usr/sbin/useradd

Requires: python3-pytoml
Requires: python3-semantic_version
Requires: libgit2
Requires: libgit2-glib
Requires: python3-flask
Requires: python3-gevent
Requires: anaconda-tui
Requires: qemu-img
Requires: tar
```

**Comment by AdamWill** [comment]
aha, good catch - I was looking for `anaconda-core`.
