### ISSUE TITLE
RFE: Add a .deb package?

### ISSUE THREAD

**Issue by q2dg** [weldr/lorax#511]
I'd want to use lorax (and specifically, livemedia-creator) to generate Fedora isos from my Ubuntu workstation. Could it be possible?
Thanks!

**Comment by bcl** [comment]
It's fairly tightly integrated into the Fedora way of doing things, so I'm not sure what it would take. It's not something we're going to have time to work on, and it's fairly easy to setup a VM to run it inside of.
