### ISSUE TITLE
installer.py: The "-nodefconfig" option has been removed. Use "-no-user-config" instead. (QEMU ChangeLog/3.1)

### ISSUE THREAD

**Issue by doverride** [weldr/lorax#543]
installer.py: The "-nodefconfig" option has been removed. Use "-no-user-config" instead. (QEMU ChangeLog/3.1)

**Comment by bcl** [comment]
@doverride Which version of lorax are you using? Which version of qemu is installed?

**Comment by bofh80** [comment]
Looks like 3.1 is available in rawhide
https://ipads.se.sjtu.edu.cn:1312/qiuzhe/qemu-official/commit/f29a56147b66845914d0a645bf9b4c5bb9a6af57 Introduction of -no-user-config

https://git.qemu.org/?p=qemu.git;a=commit;h=2feac451d2b4492aa8a67f40bd20dd351941d1a2
deprecation of -nodefconfig
