### ISSUE TITLE
in src/pylorax/installer.py on line 386 you reference "targeted"

### ISSUE THREAD

**Issue by doverride** [weldr/lorax#544]
It is better to make that variable and add a option (something like) "--selinux-policy-model targeted"
That way we can tell it about the policy to reference without having to edit installer.py

**Comment by bcl** [comment]
I really don't want to add even more cmdline args to select things that never get used. We always use targeted, and I don't see any reason to use anything else.

**Comment by doverride** [comment]
How about then sourcing /etc/selinux/config and referencing /etc/selinux/$SELINUXTYPE/contexts ...
What you say is just narrow minded. Fedora ships also MLS and Minimal policy.

**Comment by larskarlitski** [comment]
> What you say is just narrow minded.

I have no opinion on the subject matter, but please keep the conversation friendly.
