### ISSUE TITLE
systemd-tmpfiles deletes files in lorax' temporary fs tree

### ISSUE THREAD

**Issue by larskarlitski** [weldr/lorax#570]
`systemd-tmpfiles` deletes files older than 30 days (by default). When lorax does a `dnf installroot` in `/var/tmp`, some of the unpacked files are older than that. They're deleted if `systemd-tmpfiles` and `lorax` run at the same time.

There's a fix proposed upstream (https://github.com/systemd/systemd/pull/11482) which allows porgrams to take a BSD lock to signal that a directory should not be descended into.

**Comment by bcl** [comment]
I'm working on a fix for this that we can push until things are available upstream.

**Comment by bcl** [comment]
https://github.com/weldr/lorax/pull/571 should fix this for now, and since it is using flock in the future we just need to drop the /usr/lib/tmpfiles.d/lorax.conf when systemd is updated.

**Comment by bcl** [comment]
Closing this, it is in all the active branches now.
