### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by jorika** [weldr/lorax#614]
Hello,

I am trying to create bootable PXE Fedora based on this article - https://linux.xvx.cz/2017/07/how-to-...ive-image.html
Fedora 29
But at the end I got the message "livemedia-creator: 'NoneType' object is not callable.

Could you help me to resolve this issue?

Thanks! 

![wp_20190219_15_36_52_pro-min](https://user-images.githubusercontent.com/24241233/53054284-e89c0a80-3471-11e9-8f68-e00b6c89dde4.jpg)
![wp_20190219_15_37_06_pro-min](https://user-images.githubusercontent.com/24241233/53054285-e89c0a80-3471-11e9-93b6-3ead5e7ca64b.jpg)
![wp_20190219_15_37_36_pro-min](https://user-images.githubusercontent.com/24241233/53054287-e89c0a80-3471-11e9-98ae-9646ffd3334f.jpg)

**Comment by stastm12** [comment]
We ran into the same error.
The solution was to go back to an older version (In our case: lorax-28.10-1.fc28 as we are using Fedora 28).

**Comment by bcl** [comment]
Which version are you using. I just pushed lorax-29.26-1 stable this week, it should fix the NoneType bug. https://bodhi.fedoraproject.org/updates/FEDORA-2019-08018846dd

**Comment by jorika** [comment]
lorax-28.10-1.fc28 is fine for me, thanks, it works!

**Comment by sirredbeard** [comment]
I found this thread after running into this bug as well.

I am using lorax-29.26-1 and still hitting it.

![83775a12-7b90-4ddc-acfb-ff4bdc165956 png](https://user-images.githubusercontent.com/33820650/53488452-45905580-3a5c-11e9-910c-79c3094a2a5d.jpg)
