### ISSUE TITLE
Blueprint configuration file (.toml) cannot get deleted.

### ISSUE THREAD

**Issue by henrywang** [weldr/lorax#621]
After deleted blueprint from UI, the configuration file in `/var/lib/lorax/composer/blueprints/git/workspace/master/` folder cannot get deleted accordingly.

**Comment by bcl** [comment]
Good catch. It hopefully doesn't cause any real problems since the list of blueprints does not show it anymore, but yes if you do a depsolve, etc. on the deleted blueprint it will still return a result.
Please files bugzilla bugs against the relevant branches.

**Comment by bcl** [comment]
Also, I noticed that you can build a deleted blueprint if you know the name, but that doesn't depend on it being in the workspace so I'll file separate bugs for that.
