### ISSUE TITLE
provide name in source info

### ISSUE THREAD

**Issue by jgiardino** [weldr/lorax#665]
It looks like this api call is returning an `id` instead of a `name`:
`/api/v0/projects/source/info/<source-name>`

If that's the case, can the information being returned include the name? This is a little more UI friendly than the id.

cc @larskarlitski @andreasn

**Comment by bcl** [comment]
I can add an 'id' field and switch name to use the name (much of the time they are the same). Everything we do uses the id to reference the repository, so make sure you don't pass the name to the API.

**Comment by bcl** [comment]
The system repo names have variables in them, eg. "Fedora $releasever - $basearch"
I'm not sure what the best way to handle displaying those is, if the API returns their values and they get passed back in as a new or modified source you then end up with the variable hard-coded.
