### ISSUE TITLE
Calling API "api/v0/blueprints/depsolve/<blueprint name>" on rhel7 is slower

### ISSUE THREAD

**Issue by henrywang** [weldr/lorax#676]
Environment:
RHEL 7.6: lorax-composer-19.7.27-1.el7.x86_64
Fedora 29: lorax-composer-29.27-1.fc29.x86_64
Issue:
Calling API "api/v0/blueprints/depsolve/<blueprint name>" on rhel7 is slower than on fedora 29
Fedora 29:
```shell
sudo time curl --unix-socket /run/weldr/api.socket http://localhost:4000/api/v0/blueprints/depsolve/example-development
0.00user 0.00system 0:00.06elapsed 12%CPU
```
RHEL 7.6:
```shell
time curl --unix-socket /run/weldr/api.socket http://localhost:4000/api/v0/blueprints/depsolve/example-development

real    0m7.474s
user    0m0.037s
sys     0m0.030s
```
So running on Fedora looks much faster than on RHEL.

**Comment by bcl** [comment]
You cannot compare the two. RHEL7 uses yum and F29 uses dnf.
