### ISSUE TITLE
Domain resolution failure during build

### ISSUE THREAD

**Issue by dlohin** [weldr/lorax#713]
I followed this process:
https://fedoraproject.org/wiki/Livemedia-creator-_How_to_create_and_use_a_Live_CD

And I am trying to add files from Github to the built image.  My idea was to download a file off of raw.github, but realized I couldn't because domain name resolution kept failing inside of %post.  I noticed that there is no resolv.conf and I can ping by IP, just not domain name?

Is there something I need to change inside of Mock, my kickstart or elsewhere?

The below output from from the anaconda log:
resolv.conf
cat: /etc/resolv.conf: No such file or directory
ping google
ping: google.com: Name or service not known
ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=12.6 ms

**Comment by bcl** [comment]
That's going to be something wrong with your mock setup. DNS needs to be working for it to download packages.

**Comment by dlohin** [comment]
Mock is able to do dns lookups before i run the livemedia creator command.  I am able to ping by name and ip.

**Comment by dlohin** [comment]
To add to this, packages are being downloaded.  It is only when I do wget commands or ping inside of my post in the kickstart that Domain resolution fails.

Inside of Mock:
<mock-chroot> sh-5.0# ping google.com
PING google.com (172.217.0.142) 56(84) bytes of data.
64 bytes from atl14s77-in-f14.1e100.net (172.217.0.142): icmp_seq=1 ttl=47 time=38.6 ms

The packages are working fine as well.  I am guessing I am misunderstanding how networking works inside of Mock and Anaconda?

My networking in the kickstart is set to:
network  --bootproto=dhcp --device=link --nameserver=8.8.8.8 --activate

(I also tried without setting the nameserver)

Is there something simple I am overlooking?

**Comment by dlohin** [comment]
I was able to fix it by adding this to post:

cat > /etc/resolv.conf << EOF
nameserver <internal DNS>
EOF


Still not understanding why this is needed, but it worked.
