### ISSUE TITLE
CmdlineError: Missing package: grub2-efi-*-cdboot.

### ISSUE THREAD

**Issue by geislermatt** [weldr/lorax#762]
Getting this error using out-of-the-box blueprint....

[lorax-composer]# tail /var/log/lorax-composer/program.log
[Errno 25] Inappropriate ioctl for device
anaconda 21.48.22.147-1 for Red Hat Enterprise Linux 7 (pre-release) started.
Starting automated install................
The installation was stopped due to an error which occurred while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
The exact error message is:

CmdlineError: Missing package: grub2-efi-*-cdboot.

The installer will now terminate.
Running... umount /mnt/sysimage/

**Comment by bcl** [comment]
You need to make sure that you have the optional repository enabled.
