### ISSUE TITLE
per-build composer logs

### ISSUE THREAD

**Issue by bcl** [weldr/lorax#770]
Right now the only logs a user has API access to are the anaconda logs, but there are also composer/pylorax logs related to the build. We need to figure out how to include *only* the logs associated with that build and add them to what's available via the API.

Maybe temporarily add a log handler while the build is running?

**Comment by evan-goode** [comment]
The temporary log handler seems like a good way to do it: https://github.com/weldr/lorax/compare/master...evan-goode:770-composer-logs

Do you think /compose/log/<uuid> should try to merge the anaconda and composer logs, or should there just be a separate route for the composer log?

**Comment by bcl** [comment]
I think separate logs are best, I think merging them would make them harder to read.
We also need to capture the "program" logs and "dnf" logs in the same way.

**Comment by bcl** [comment]
This was fixed by commit 90626f97b64bf53a416b1a91c9c8a9980613d3fb
