### ISSUE TITLE
Man page shows incorrect options

### ISSUE THREAD

**Issue by hadess** [weldr/lorax#784]
The descriptions of the options all show the options as taking one `-` sign, instead of 2, for example:
```
   Named Arguments
       -make-iso
              Build a live iso

              Default: False
```

`-make-iso` should be `--make-iso`

Short version of the options show the same problem:
```
   Named Arguments
       V      show program's version number and exit
```

`V` should be `-V`

**Comment by evan-goode** [comment]
https://github.com/ribozz/sphinx-argparse/issues/80 may be related.

**Comment by bcl** [comment]
Yeah, seems like docutils is the actual problem - https://sourceforge.net/p/docutils/mailman/message/36221658/
I suppose I could post-process the manpages until a fix makes its way into Fedora.

**Comment by evan-goode** [comment]
If we're post-processing, `sed -E "s/^\.B(\S)/\.B \1/gm` would address the problem as I understand it.

**Comment by bcl** [comment]
Upstream bug for this. https://sourceforge.net/p/docutils/bugs/380/
