### ISSUE TITLE
service fails when metadata fails to update

### ISSUE THREAD

**Issue by jgiardino** [weldr/lorax#791]
When trying to start lorax-composer in cockpit, I would get failure messages like this one:
`Failed to update metadata: Conflicting defaults with repo 'appstream-nightly': Conflicting profile defaults when merging defaults for module virt`

The only way to fix this was to run this command and remove all repos:
`rm -rf /var/lib/lorax/composer/repos.d/`

But from the context of the UI or CLI, there was nothing informing the user about this failure or how to fix it. Is this something that could be handled differently?

cc'ing @larskarlitski on this to provide any additional clarification

**Comment by bcl** [comment]
When the service fails to start you should be able to use cockpit to view the logs for lorax-composer.socket (and .service) to get more details.

As for the error itself, can you describe how to get the system into that state? I haven't seen that error before, and it sounds like it could be a dnf bug if you hadn't done anything odd to the system (eg. adding unsupported extra repos).
