### ISSUE TITLE
No docs on how to enable debug

### ISSUE THREAD

**Issue by hadess** [weldr/lorax#809]
Reading `src/pylorax/__init__.py` I think I'm supposed to have something like:
```
[lorax]
debug = 1
```
in `/etc/lorax/lorax.conf`, or in `etc/lorax.conf` (is that read when setting `PYTHONPATH=./src/` ? I'm guessing not), but that doesn't seem to do anything.

The [Debugging problems](https://weldr.io/lorax/livemedia-creator.html#debugging-problems) section of the docs also don't mention how to enable debug.

Ideally, the configuration would be documented (which tools/libraries use it, under which circumstances) and each of the command-line tool would have a `-v` (verbose) or `-d`/`--debug` option to make this easier.

**Comment by bcl** [comment]
Debugging is actually always enabled, unless you set debug = 0 in a config file.

**Comment by hadess** [comment]
> Debugging is actually always enabled, unless you set debug = 0 in a config file.

Maybe putting that in the Debugging problems section might be a good idea.
