### ISSUE TITLE
pylorax: --dracut-arg(s) is broken both as documented and as implemented (which are also completely different)

### ISSUE THREAD

**Issue by gmt** [weldr/lorax#844]
- The undocumented command-line option --dracut-args is implemented as though it is supposed to allow us to gut-and-replace the arguments to dracut.  However, it is only allowed to be provided once, and the arguments to dracut are determined by splitting the provided string with ' ' (the space character).  Unfortunately, we need to pass arguments to dracut which contain spaces.  So it cannot be used except perhaps in a few degenerate cases.

- The argument --dracut-arg, which is documented but does not exist in pylorax, is semantically superior: it lets us achieve what the undocumented-but-implemented option intends to let us achieve by providing the --dracut-arg argument repeatedly.  However this is a fairly blunt instrument.  For example, here is how the documented option would serve as a noop by implementing the defaults already built into pylorax:```--dracut-args --xz --dracut-args --add --dracut-args "livenet dmsquash-live convertfs pollcdrom qemu qemu-net" --dracut-args --omit --dracut-args plymouth --dracut-args --no-hostonly --dracut-args --debug --dracut-args --no-early-microcode```  As can be seen above, this is a fairly tedious syntax.  I suppose it is semantically sufficient, but it forces us to choose between benefiting from the module defaults built into pylorax or the ones built into dracut, which is less than ideal as it forces us to peer "through" pylorax into the guts of the dracut, to figure out what will actually happen.

Since the existing implementation is broken semantically and the documented implementation is crippled functionally, perhaps both should go in the bit-bucket, and pylorax should consider a re-implementation from scratch, using the same type of command-line arguments used by dracut (i.e., support "--add-dracut-module" "--remove-dracut-module", and various dracut-passthrough options, i.e., "--dracut-no-xz")?

**Comment by bcl** [comment]
I think I have a better way to deal with this, see #943 which adds a --dracut-conf cmdline arg so you can just point it to a config file. Much easier than passing args.

Also, some of your assertions are incorrect. There is no --dracut-args option, just --dracut-arg (internally it stores into opts.dracut_args so maybe that's what you meant). And spaces should be working fine, I can do `--dracut-arg '--add livenet dmsquash-live convertfs pollcdrom qemu qemu-net'` just fine. It splits on the first space, and ignores the rest. In bash you have to single-quote this.

It is confusing though, and I've never really been happy with how awkward it is. I think using a config file is much cleaner.

**Comment by gmt** [comment]
That sure sounds like reasonable solution to me.

IIRC the official documentation says 'dracut-args' somewhere (man page?)

I myself managed to mix the two up, more than once, above, I notice :).

As for spaces: perhaps I was using ```--dracut-arg='foo bar'```?   By now, I must confess, my cerebral cold-storage lossy compression cron job seems to have blurred my recollection of the whole thing down to just a few pixels.

**Comment by bcl** [comment]
> IIRC the official documentation says 'dracut-args' somewhere (man page?)

Found it. It was in the comment above DRACUT_DEFAULT in creator.py

**Comment by bcl** [comment]
Fixed by #943
