### ISSUE TITLE
livemedia-creator --title

### ISSUE THREAD

**Issue by saamalik** [weldr/lorax#863]
Hi - according to the [documentation](https://weldr.io/lorax/livemedia-creator.html), _livemedia-creator_ option `--title <...>`, is used in bootloader config files:

    Substituted for @TITLE@ in bootloader config files

    Default: "Linux Live Media"

However, none of the config files use `@TITLE@`, nor is it referenced anywhere in the code. I would recommend we remove it from the docs.

**Comment by bcl** [comment]
Thanks for catching that

**Comment by AdamWill** [comment]
I am not convinced this is actually unused. I believe it's used somehow for producing live image file names. See https://pagure.io/releng/failed-composes/issue/562#comment-612509 .

**Comment by AdamWill** [comment]
Oh, OK, so the `--title` arg is really not used, the filename is coming from the `--iso-name` arg. But I think https://pagure.io/pungi-fedora/pull-request/799 is probably still wrong.
