### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by bsomani** [weldr/lorax#873]
Hi,

I am trying to build boot image of my custom centos7 
trying to build using 

sudo lorax -p "My ProductName" -v 5.0.0 -r CentOS-7.6.1810 -s 'pwd' --tmp=`pwd`/tmpb ./results/

running runtime-postinstall.tmpl
2019-10-17 06:59:36,575: template command error in runtime-postinstall.tmpl:
template command error in runtime-postinstall.tmpl:
2019-10-17 06:59:36,575:   move usr/share/anaconda/restart-anaconda usr/bin
  move usr/share/anaconda/restart-anaconda usr/bin
2019-10-17 06:59:36,580:   OSError: [Errno 2] No such file or directory
  OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/sbin/lorax", line 425, in <module>
    main(sys.argv)
  File "/sbin/lorax", line 304, in main
    user_dracut_args=opts.dracut_args)
  File "/usr/lib/python2.7/site-packages/pylorax/__init__.py", line 268, in run
    rb.postinstall()
  File "/usr/lib/python2.7/site-packages/pylorax/treebuilder.py", line 136, in postinstall
    self._runner.run("runtime-postinstall.tmpl", configdir=configdir_path)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 194, in run
    self._run(commands)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 213, in _run
    f(*args)
  File "/usr/lib/python2.7/site-packages/pylorax/ltmpl.py", line 391, in move
    mvfile(self._out(src), self._out(dest))
  File "/usr/lib/python2.7/site-packages/pylorax/sysutils.py", line 98, in mvfile
    os.rename(src, dst)
OSError: [Errno 2] No such file or directory

the file usr/share/anaconda/restart-anaconda is present on system.

Any help in this regard?

Regards,
Bharat

**Comment by bsomani** [comment]
Thanks a lot Brian for your valuable reply, 

So to add some background,

Initially when our product was running on centos6 and we want to create boot image which will install CentOS6 with few modifications during installation process like Add an optional End User License (EULA) screen, remove unwanted screens and add our logo and text. Hence we have downloaded centos 6 supplied anaconda source. Then we modified it according to our requirement and created updated anaconda.rpm on centos 6.5
Then we created  RPM repository with all the required packages (based of centos 6.5) using createrepo and then finally used buildinstall utility to create that boot image.

This boot image was created successfully and used to install CentOS6

Now our product is moved to centos 7 and we wanted to install this centos 7 using same boot image (based on Centos 6.5) so that we dont need to download new anaconda again and make modifications.

But by looking at centos7 everything iso we found that there are few more things as part of boot image like liveos/squashfs.img, efi/grubx64 etc,

So to produce this updated boot image which is capable of installing centos 7, we copied old repository (centos 6.5 based) which contains our modified anaconda rpm and other required packages on centos7 system.
To create the boot image, we found that buildinstall is replaced by lorax in centos 7. Hence we are trying to use lorax to create the boot image.
while running lorax command we found above issue.

On the centos 7 where we are running lorax command, usr/share/anaconda/restart-anaconda file is present. But still we are getting this OSError: [Errno 2] No such file or directory 

Do you mean my old repository (centos 6.5 based) which I am providing to lorax command is not containing the usr/share/anaconda/restart-anaconda file? If this is the case then is there any way i can solve this issue?

Your help in this is highly appreciated.

**Comment by bcl** [comment]
You cannot use CentOS7 to install CentOS6, or build a boot.iso using CentOS6 content. You will need to make your changes to the CentOS7 anaconda, etc.
