### ISSUE TITLE
Option --qemu-arg not sent to Qemu install

### ISSUE THREAD

**Issue by saamalik** [weldr/lorax#893]
Hi, the livemedia-creator option `--qemu-arg` is not being passed down to [QemuInstall](https://github.com/weldr/lorax/blob/c6fcf9d1eb1bad657bbb6dffd340d950abc5eaf8/src/pylorax/installer.py).

Ideally, I'd like to mount a host directory in the Qemu instance, e.g:

    --qemu-arg "-virtfs local,path=/tmp/,security_model=passthrough,mnt_tag=v_tmp" \

And in the guest, in the kickstart, mount the directory:

    mount -t 9p -o trans=virtio v_tmp /mnt

Thanks!

**Comment by saamalik** [comment]
BTW do you know of any workaround for the timebeing?

**Comment by bcl** [comment]
Sorry, that's not meant for passing to qemu. It's for controlling qemu-img which is used to make the qcow2 images:
    "Arguments to pass to qemu-img. Pass once for each argument, they will be used for ALL calls to qemu-img."
