### ISSUE TITLE
Adding a local rpm and a shell script?

### ISSUE THREAD

**Issue by kodaman2** [weldr/lorax#928]
Questions: 
- I have an rpm from intel that we use for raid configuration. Is it possible to add to TOML? Or do you recommend also to upload to a github repo?
- Also want to add some files, and directories, would this be easier to do with a github repo or something else?

If none of this is natively available? Perhaps two more toml options would be to add a flag to the packages like local=true, path=/Downloads/some/tool, and customizations.script, name=some_script, path=/Scripts/some_script.sh

Thanks for this great tool!

**Comment by bcl** [comment]
The `[[repos.git]]` feature doesn't require github, you can point it to any git repo available to the system that lorax-composer is running on. See https://weldr.io/lorax/lorax-composer.html#repos-git

If you already have an rpm the easiest way is to make it available from a repository that you add using `composer-cli sources` command. See https://weldr.io/lorax/lorax-composer.html#package-sources for the format of the sources TOML.

**Comment by kodaman2** [comment]
Thanks for the clarification on both questions.

I do think adding a script option is worth looking into it in the future. Creating a git repo just for folder structure is probably an overkill in my opinion.

Or how do you handle things that are not supported by this library?

**Comment by bcl** [comment]
Scripts are something that we are strongly against -- it leads to untraceable changes and hard to maintain configurations. The idea behind requiring either an rpm or a git repo is that there is an explicit source for the extra files, not just whatever happens to be on the build system when the image is created.

**Comment by kodaman2** [comment]
Thanks again!
