### ISSUE TITLE
rootfs goes read-only once 1.8GB of space is used

### ISSUE THREAD

**Issue by zerocarbthirty** [weldr/lorax#932]
Hi,
I created a PXE live image like this:

livemedia-creator --make-pxe-live --image-name=newDSUSz22z22a --live-rootfs-size=6 --ks newthing --iso=/isos/CentOS-7-x86_64-Minimal-1908.iso

it creates the image, when i boot the image it says that /dev/mapper/live-rw is 6GB but it always seems to run out of space and go "read only" anytime the space used is more than 1.8GB.

**Comment by bcl** [comment]
The COW filesystem uses more space than a normal bare filesystem, delete and write can cause it to run out of space sooner than expected. Also, since this is a PXE boot memory can be an issue as well.
