### ISSUE TITLE
Add the chance to install group of packages

### ISSUE THREAD

**Issue by alosadagrande** [weldr/lorax#973]
Hi,

I could not find anywhere, but I guess there is no functionality to allow installation of groups of packages. For instance the Virtualization or the Server with GUI could be at some point interesting when creating new images:

```
$ yum group list
Last metadata expiration check: 0:37:30 ago on Fri 28 Feb 2020 11:51:16 AM UTC.
Available Environment Groups:
   Server with GUI
   Server
   Minimal Install
   Workstation
   Custom Operating System
Installed Environment Groups:
   Virtualization Host
Available Groups:
   Container Management
   .NET Core Development
   RPM Development Tools
   Development Tools
   Graphical Administration Tools
   Headless Management
   Legacy UNIX Compatibility
   Network Servers
   Scientific Support
   Security Tools
   Smart Card Support
   System Tools
```

**Comment by bcl** [comment]
Could you be more specific about what you are trying to do? The lorax project includes several different ways to create images. lorax for the anaconda boot.iso, livemedia-creator for kickstart driven image creation (groups are supported by the standard kickstart @group syntax), and lorax-composer for blueprint image creation where groups are supported by the [[group]] section.

**Comment by alosadagrande** [comment]
Hi @bcl, yes apologies for not being specific. I am using lorax-composer for blueprint image creation and I was wondering if there was an option to install group of packages. I did not realize about the option [[groups]] which is the one I was looking for.

Thank you for your help
